### ISSUE TITLE
Increase CPU needed for Redash

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#1238]
Title of ticket: 

#### Description
Need to increase CPU for dev server - change from small to medium. This is needed for redash dashboard.
Platform team has requested we monitor usage using Sysdig to convey our current utilization

#### Dependencies
Are there any dependencies?

#### DOD
- [ ] Request CPU
- [ ] Generate Sysdig report to support request
- [ ] 
- [ ]

**Comment by mpilchar** [comment]
@acoard-aot  per sprint planning discussion, please fine tune our approach for this task and ensure any related tasks are captured

**Comment by acoard-aot** [comment]
The work for this is specced out in #1240.  The task is first about monitoring and/or reducing current CPU/mem usage, so that we have enough space for redash and other future components.

Redash itself looks like it is not needed in our environment as we're getting a new openshit env specific for ETL and reporting.  As such, we should close this task and use #1240 which does not specifically mention redash.

**Comment by mpilchar** [comment]
Replace with #1240 - closing
