### ISSUE TITLE
Resources Over Utilized - File Watcher Needs increased Memory

### ISSUE THREAD

**Issue by JHarrietha-AOT** [bcgov/foi-flow#124]
**Describe the bug in current situation**
When users add large excel files (100MB+) system resources are being over utlized which is resulting in failure of PDF's being produced.

**Link bug to the User Story**

**Impact of this bug**
Large Excel files can not be converted into PDF, unless resources and increased and tested further 

**Chance of Occurring (high/medium/low/very low)**
Not sure, need more information of average size of existing requests.

Medium - We are testing with a file that is requested.

**Pre Conditions: which Env, any pre-requisites or assumptions to execute steps?**

**Steps to Reproduce**
1. Go to file watcher
2. Add multiple large Excel file (AA-2021-44444)
3. Unable to create PDF for files/Failed in Log

**Actual/ observed behaviour/ results**

**Expected behaviour**
Files should be converted to PDF

**Screenshots/ Visual Reference/ Source**
![MicrosoftTeams-image1ec2c37e0081bb5a740ae527236885a0b9eae7af7e5e63249cbff53c3d118b52.png](https://images.zenhubusercontent.com/6081a3ba692e484184671a59/c47d2f7b-225e-40bb-8367-b11cfd06ce5b)

**Comment by lmullane** [comment]
I requested  our IMB increase RAM/Physical memory to 16 GB and CPU to 8 cores for the TEST VM on PENGUIN.

**Comment by MatthewPMorris** [comment]
Resource increase is scheduled for test VM between Noon to 1PM today

**Comment by lmullane** [comment]
Thanks, @MatthewPMorris

**Comment by m-prodan** [comment]
Additional resources requested for PELICAN prod VM - 32 gb of RAM + 8 cores

**Comment by m-prodan** [comment]
Additional resources scheduled to be deployed at 4PM today, June 21. Downtime expected to be 1 hour.

**Comment by abin-aot** [comment]
As per the testing , reviewing the resource utilization based on the concurrent "File Uploads" onto the LAN there were several tests done.  Its found all the normal use cases are working perfectly. But there are some minority set of excel files, which has 800,000 rows / 35MB of file size, when those kind of files comes in a group (> 7) , concurrently at given point of time, then server is getting freeze.  This point is discussed with the team, and its being understood that this is a very edge case scenario. 

Being said that, we are planning to monitor the PELICAN Server after production release for a period of 1 month, through a remote resource monitoring set up/service if possible, and if we see there is a much noticeable period of time in a business week, where the resources(Memory, CPU) are higher than 75% of utilization. Then, we will bring an alternative code logic to process heavier files as nightly job. So that we wont affect the majority of the normal file processing.

@mpilchar @m-prodan @lmullane
