### ISSUE TITLE
ETL Deployment and Scheduling 

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#1304]
Title of ticket: 

#### Description
Summarize issue 

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Set up Integration Services, SQL Agent Permission etc on DEV, TEST .
- [x] Deployment to TEST, DEV, PROD
- [x]  Confirm the FW rules, access to OPENSHIFT from DMZ Servers.
- [ ]  
- [ ] 
- [ ]

Note : Production ETL deployment DODs/Task moved to #1746, due to wait on STRA approval

**Comment by abin-aot** [comment]
removing DOD to deploy to PROD, since STRA is not approved to move live data. So , effort can be reduced to 5 from 8. Also, as of today - we observed an DB functions mismatch within the same version of AXIS DB on DEV, TEST and PROD. which has been reported to IMB -" FOIMOD-68" on IMB JIRA.

DODs moving 

1. DO a trial deployment to PROD to confirm the access, FW rules
