### ISSUE TITLE
Troubleshooting for file conversion

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#143]
Title of ticket: 

#### Description
Determine a procedure or go to person for file conversion mishaps

#### DOD
- [ ] issues? alerts
- [ ]

**Comment by lmullane** [comment]
@abin-aot I've posed the questions to the IMB.

**Comment by abin-aot** [comment]
MIME-Version: 1.0
Date: Thu, 24 Jun 2021 16:27:53 -0700
References: <0EB26310-8792-4603-A8AE-A374562D87E0@gov.bc.ca> <f0771528cef54a2495afa9ce6ec4e7f2@gov.bc.ca> <CAMTKs6M59uPgqSJMT5MxM6jqujSutmdyV-Ss36AfrWdLnU2v_A@mail.gmail.com> <5a062b38977844129e7926225d338439@gov.bc.ca> <CAMTKs6MM83=KrLTWGoCFyLAOskCoceS9ZWux5Q90r1tPeNmonA@mail.gmail.com> <cbba47644297411185215a6ea83bd738@gov.bc.ca>
In-Reply-To: <cbba47644297411185215a6ea83bd738@gov.bc.ca>
Message-ID: <CAMTKs6Ov-5KpNihNoh6WZHOR3UVF+gaPCqmUyLBaSzQPSNHcbw@mail.gmail.com>
Subject: Re: Process for dealing with VM issues
From: Abin Antony <abin.antony@aot-technologies.com>
To: "Smyth, David CITZ:EX" <David.Smyth@gov.bc.ca>
Cc: "Mullane, Loren CITZ:EX" <Loren.Mullane@gov.bc.ca>, "Punnett, Alexander CITZ:EX" <Alexander.Punnett@gov.bc.ca>, "Morris, Matthew CITZ:EX" <Matthew.Morris@gov.bc.ca>
Content-Type: multipart/alternative; boundary="00000000000064120c05c58b5f83"

--00000000000064120c05c58b5f83
Content-Type: text/plain; charset="UTF-8"
Content-Transfer-Encoding: quoted-printable

Ok thanks for the update. Primarily , RAM(memory) & CPU,  if those are
above 75% of utilization, we prefer to get  immediate alerts, since those
are our pain points. Disks, network i/o latency is good to have.

Can we get a weekly report of these resources as well, just to be aware of
the pattern ? Any thoughts? Advanced apologies, if I am asking too much.
This is one of the main reasons for enquiring about a remote web based
monitoring tool. At BC Assessment we were using PRTG , to monitor my
Production servers usage  all the time and can set up notifications as
required.


On Thu, Jun 24, 2021 at 3:33 PM Smyth, David CITZ:EX <David.Smyth@gov.bc.ca=
>
wrote:

> Abin,
>
> Nagios is email only. Matt and Alexander can install the client. We would
> need to understand what you would like to be alerted on. (cpu, disk,
> services, etc..)
>
> I=E2=80=99ve enclosed a sample one. You get emails only the state change.=
 Nagios
> scans the environments every 5 mins.
>
> Dave
>
>
>
>
>
> *From:* Abin Antony <abin.antony@aot-technologies.com>
> *Sent:* June 24, 2021 3:00 PM
> *To:* Smyth, David CITZ:EX <David.Smyth@gov.bc.ca>
> *Cc:* Mullane, Loren CITZ:EX <Loren.Mullane@gov.bc.ca>; Prodan, Matthew
> CITZ:EX <Matthew.Prodan@gov.bc.ca>; Andrews, Arielle CITZ:EX <
> Arielle.Andrews@gov.bc.ca>; Pilchar, Molly CITZ:EX <
> Molly.Pilchar@gov.bc.ca>; Shutko, Craig CITZ:EX <Craig.Shutko@gov.bc.ca>;
> Punnett, Alexander CITZ:EX <Alexander.Punnett@gov.bc.ca>; Morris, Matthew
> CITZ:EX <Matthew.Morris@gov.bc.ca>
> *Subject:* Re: Process for dealing with VM issues
>
>
>
> *[EXTERNAL] **This email came from an external source. Only open
> attachments or links that you are expecting from a known sender.*
>
>
>
> A delayed aggregate of accuracy just before 5 minutes is good to start
> with. We don't need that app to be accessible publicly or on DMZ, since I
> can login to VPN(Cisco) and access it.
>
>
>
> How about providing access to Nagio to monitor these servers?
>
>
>
> On Thu, Jun 24, 2021 at 2:45 PM Smyth, David CITZ:EX <
> David.Smyth@gov.bc.ca> wrote:
>
> Abin,
>
> I=E2=80=99m not aware of any web based types of tools for monitoring that=
 we could
> install. Are you looking for Realtime or delayed aggerate. If it=E2=80=99=
s delayed
> aggerate ( 5mins) I think we have a solution from the vendor call BC
> healthcheck??
>
>
>
> The VM is in Zone B, the security model/firewalls would make getting web
> traffic information to the DMZ very hard. A solution would be need to
> wrapped around VPN solution to pass information out to the DMZ.
>
> The security models are Zone A (most protective), Zone B , DMZ, Internet.
> A security zone is designed so it can only pass traffic to one layer abov=
e
> or below. For us to talk to Zone A we need to use a special vpn to tunnel
> to it.
>
>
>
> Dave
>
> *From:* Abin Antony <abin.antony@aot-technologies.com>
> *Sent:* June 24, 2021 2:29 PM
> *To:* Smyth, David CITZ:EX <David.Smyth@gov.bc.ca>
> *Cc:* Mullane, Loren CITZ:EX <Loren.Mullane@gov.bc.ca>; Prodan, Matthew
> CITZ:EX <Matthew.Prodan@gov.bc.ca>; Andrews, Arielle CITZ:EX <
> Arielle.Andrews@gov.bc.ca>; Pilchar, Molly CITZ:EX <
> Molly.Pilchar@gov.bc.ca>; Shutko, Craig CITZ:EX <Craig.Shutko@gov.bc.ca>;
> Punnett, Alexander CITZ:EX <Alexander.Punnett@gov.bc.ca>; Morris, Matthew
> CITZ:EX <Matthew.Morris@gov.bc.ca>
> *Subject:* Re: Process for dealing with VM issues
>
>
>
> *[EXTERNAL] **This email came from an external source. Only open
> attachments or links that you are expecting from a known sender.*
>
>
>
> Hi Dave,
>
>
>
> it's a typo I guess on the email. We were looking for a "remote"
> monitoring tool - web based, so that we can see resource utilization on t=
he
> server without logging in. If we can get access to that tool specific to
> our servers , then it will be helpful.
>
>
>
> On Thu, Jun 24, 2021 at 2:05 PM Smyth, David CITZ:EX <
> David.Smyth@gov.bc.ca> wrote:
>
> Loren,
>
>    - Who is our contact person in case an issue arises that we cannot
>    solve ourselves?
>
> The IMB is your escalation point, Matt and Alexander and myself. We can
> mediate your request to the vendor
>
>
>
>    - Is there any way to receive automated alerts if a server goes down?
>
> The vendor has monitoring that alerts them only of outages. If they detec=
t
> a server is down they will investigate.
>
> We have a central monitoring application called Nagios for monitoring. It
> can alert us by email if we have outages or services warnings (ie low Dis=
k
> space). We also can monitor services state changes as well. If you like w=
e
> can add the Nagios client to the VM
>
>
>
>    - Is there an interface that we can login into for remove monitoring?
>
> The vendor monitoring is not possible to remove. Part of the contract.
>
>
>
> Also the vendor has an establish Sunday morning change windows from 6-9am
> where they perform operational maintenance. Sometimes it causes
> disruptions.
>
> The vendor manages the security patching of the OS. They will schedule a
> date for patching and require approval by Matt or Alexander to proceed.
>
> Typically we stay out of the C: drive and install any applications to
> other drives. The managing of small amount of working space on the C driv=
e
> we normally leave to the vendor.
>
>
>
> Dave
>
>
>
> *From:* Mullane, Loren CITZ:EX <Loren.Mullane@gov.bc.ca>
> *Sent:* June 24, 2021 1:31 PM
> *To:* Smyth, David CITZ:EX <David.Smyth@gov.bc.ca>
> *Cc:* Prodan, Matthew CITZ:EX <Matthew.Prodan@gov.bc.ca>; Andrews,
> Arielle CITZ:EX <Arielle.Andrews@gov.bc.ca>; Abin Antony <
> abin.antony@aot-technologies.com>; Pilchar, Molly CITZ:EX <
> Molly.Pilchar@gov.bc.ca>
> *Subject:* Process for dealing with VM issues
>
>
>
> Hi David,
>
>
>
> We had an access issue with the VM this week, which your team was able to
> resolve in a timely fashion.
>
> A few questions for you if we need future support on the VM:
>
>
>
>    - Who is our contact person in case an issue arises that we cannot
>    solve ourselves?
>    - Is there any way to receive automated alerts if a server goes down?
>    - Is there an interface that we can login into for remove monitoring?
>
>
>
> Appreciate your insight here.
>
>
>
> Best,
>
>
>
> Loren
>
>
>
>
>
>

--00000000000064120c05c58b5f83
Content-Type: text/html; charset="UTF-8"
Content-Transfer-Encoding: quoted-printable

<div dir=3D"ltr"><div dir=3D"ltr"><br><div>Ok thanks for the update. Primar=
ily=C2=A0, RAM(memory) &amp; CPU,=C2=A0 if those are above 75% of utilizati=
on, we prefer to get=C2=A0 immediate alerts,=C2=A0since those are our pain =
points. Disks, network i/o latency is good to have.=C2=A0</div><div><br></d=
iv><div>Can we get a weekly report of these resources as well, just to be a=
ware of the pattern ? Any thoughts? Advanced apologies, if I am asking too=
=C2=A0much. This is one of the main reasons for enquiring=C2=A0about a remo=
te web based monitoring tool. At BC Assessment we were using PRTG , to moni=
tor my Production servers usage=C2=A0 all the time and can set up notificat=
ions as required.=C2=A0</div><div><br></div></div><br><div class=3D"gmail_q=
uote"><div dir=3D"ltr" class=3D"gmail_attr">On Thu, Jun 24, 2021 at 3:33 PM=
 Smyth, David CITZ:EX &lt;<a href=3D"mailto:David.Smyth@gov.bc.ca">David.Sm=
yth@gov.bc.ca</a>&gt; wrote:<br></div><blockquote class=3D"gmail_quote" sty=
le=3D"margin:0px 0px 0px 0.8ex;border-left:1px solid rgb(204,204,204);paddi=
ng-left:1ex">





<div lang=3D"EN-CA" style=3D"overflow-wrap: break-word;">
<div class=3D"gmail-m_-5378725715241952683WordSection1">
<p class=3D"MsoNormal"><span>Abin,<u></u><u></u></span></p>
<p class=3D"MsoNormal"><span>Nagios is email only. Matt and Alexander can i=
nstall the client. We would need to understand what you would like to be al=
erted on. (cpu, disk, services, etc..)<u></u><u></u></span></p>
<p class=3D"MsoNormal"><span>I=E2=80=99ve enclosed a sample one. You get em=
ails only the state change. Nagios scans the environments every 5 mins.<u><=
/u><u></u></span></p>
<p class=3D"MsoNormal"><span>Dave <u></u><u></u></span></p>
<p class=3D"MsoNormal"><span><u></u>=C2=A0<u></u></span></p>
<p class=3D"MsoNormal"><span><u></u>=C2=A0<u></u></span></p>
<div>
<div style=3D"border-right:none;border-bottom:none;border-left:none;border-=
top:1pt solid rgb(225,225,225);padding:3pt 0cm 0cm">
<p class=3D"MsoNormal"><b><span lang=3D"EN-US">From:</span></b><span lang=
=3D"EN-US"> Abin Antony &lt;<a href=3D"mailto:abin.antony@aot-technologies.=
com" target=3D"_blank">abin.antony@aot-technologies.com</a>&gt;
<br>
<b>Sent:</b> June 24, 2021 3:00 PM<br>
<b>To:</b> Smyth, David CITZ:EX &lt;<a href=3D"mailto:David.Smyth@gov.bc.ca=
" target=3D"_blank">David.Smyth@gov.bc.ca</a>&gt;<br>
<b>Cc:</b> Mullane, Loren CITZ:EX &lt;<a href=3D"mailto:Loren.Mullane@gov.b=
c.ca" target=3D"_blank">Loren.Mullane@gov.bc.ca</a>&gt;; Prodan, Matthew CI=
TZ:EX &lt;<a href=3D"mailto:Matthew.Prodan@gov.bc.ca" target=3D"_blank">Mat=
thew.Prodan@gov.bc.ca</a>&gt;; Andrews, Arielle CITZ:EX &lt;<a href=3D"mail=
to:Arielle.Andrews@gov.bc.ca" target=3D"_blank">Arielle.Andrews@gov.bc.ca</=
a>&gt;; Pilchar, Molly CITZ:EX &lt;<a href=3D"mailto:Molly.Pilchar@gov.bc.c=
a" target=3D"_blank">Molly.Pilchar@gov.bc.ca</a>&gt;; Shutko, Craig CITZ:EX=
 &lt;<a href=3D"mailto:Craig.Shutko@gov.bc.ca" target=3D"_blank">Craig.Shut=
ko@gov.bc.ca</a>&gt;;
 Punnett, Alexander CITZ:EX &lt;<a href=3D"mailto:Alexander.Punnett@gov.bc.=
ca" target=3D"_blank">Alexander.Punnett@gov.bc.ca</a>&gt;; Morris, Matthew =
CITZ:EX &lt;<a href=3D"mailto:Matthew.Morris@gov.bc.ca" target=3D"_blank">M=
atthew.Morris@gov.bc.ca</a>&gt;<br>
<b>Subject:</b> Re: Process for dealing with VM issues<u></u><u></u></span>=
</p>
</div>
</div>
<p class=3D"MsoNormal"><u></u>=C2=A0<u></u></p>
<div style=3D"border:1pt solid rgb(156,101,0);padding:2pt">
<p class=3D"MsoNormal" style=3D"line-height:12pt;background:coral"><b><span=
 style=3D"font-size:10pt;font-family:Verdana,sans-serif;color:gold">[EXTERN=
AL]
</span></b><b><span style=3D"font-size:10pt;font-family:Verdana,sans-serif;=
color:navy">This email came from an external source. Only open attachments =
or links that you are expecting from a known sender.<u></u><u></u></span></=
b></p>
</div>
<p class=3D"MsoNormal"><u></u>=C2=A0<u></u></p>
<div>
<div>
<div>
<p class=3D"MsoNormal">A delayed aggregate of accuracy=C2=A0just before 5 m=
inutes is good to start with. We don&#39;t=C2=A0need that app to be accessi=
ble publicly or on DMZ, since I can login to VPN(Cisco) and access it.=C2=
=A0<u></u><u></u></p>
</div>
<div>
<p class=3D"MsoNormal"><u></u>=C2=A0<u></u></p>
</div>
<div>
<p class=3D"MsoNormal">How about providing access to Nagio to monitor these=
 servers?=C2=A0<u></u><u></u></p>
</div>
<p class=3D"MsoNormal"><u></u>=C2=A0<u></u></p>
<div>
<div>
<p class=3D"MsoNormal">On Thu, Jun 24, 2021 at 2:45 PM Smyth, David CITZ:EX=
 &lt;<a href=3D"mailto:David.Smyth@gov.bc.ca" target=3D"_blank">David.Smyth=
@gov.bc.ca</a>&gt; wrote:<u></u><u></u></p>
</div>
<blockquote style=3D"border-top:none;border-right:none;border-bottom:none;b=
order-left:1pt solid rgb(204,204,204);padding:0cm 0cm 0cm 6pt;margin-left:4=
.8pt;margin-right:0cm">
<div>
<div>
<p class=3D"MsoNormal">Abin,<u></u><u></u></p>
<p class=3D"MsoNormal">I=E2=80=99m not aware of any web based types of tool=
s for monitoring that we could install. Are you looking for Realtime or del=
ayed aggerate. If it=E2=80=99s delayed aggerate ( 5mins) I think we
 have a solution from the vendor call BC healthcheck??<u></u><u></u></p>
<p class=3D"MsoNormal">=C2=A0<u></u><u></u></p>
<p class=3D"MsoNormal">The VM is in Zone B, the security model/firewalls wo=
uld make getting web traffic information to the DMZ very hard. A solution w=
ould be need to wrapped around VPN solution to pass
 information out to the DMZ.<u></u><u></u></p>
<p class=3D"MsoNormal">The security models are Zone A (most protective), Zo=
ne B , DMZ, Internet. A security zone is designed so it can only pass traff=
ic to one layer above or below. For us to talk to
 Zone A we need to use a special vpn to tunnel to it.<u></u><u></u></p>
<p class=3D"MsoNormal">=C2=A0<u></u><u></u></p>
<p class=3D"MsoNormal">Dave
<u></u><u></u></p>
<div>
<div style=3D"border-right:none;border-bottom:none;border-left:none;border-=
top:1pt solid rgb(225,225,225);padding:3pt 0cm 0cm">
<p class=3D"MsoNormal"><b><span lang=3D"EN-US">From:</span></b><span lang=
=3D"EN-US"> Abin Antony &lt;<a href=3D"mailto:abin.antony@aot-technologies.=
com" target=3D"_blank">abin.antony@aot-technologies.com</a>&gt;
<br>
<b>Sent:</b> June 24, 2021 2:29 PM<br>
<b>To:</b> Smyth, David CITZ:EX &lt;<a href=3D"mailto:David.Smyth@gov.bc.ca=
" target=3D"_blank">David.Smyth@gov.bc.ca</a>&gt;<br>
<b>Cc:</b> Mullane, Loren CITZ:EX &lt;<a href=3D"mailto:Loren.Mullane@gov.b=
c.ca" target=3D"_blank">Loren.Mullane@gov.bc.ca</a>&gt;; Prodan, Matthew CI=
TZ:EX &lt;<a href=3D"mailto:Matthew.Prodan@gov.bc.ca" target=3D"_blank">Mat=
thew.Prodan@gov.bc.ca</a>&gt;; Andrews, Arielle CITZ:EX
 &lt;<a href=3D"mailto:Arielle.Andrews@gov.bc.ca" target=3D"_blank">Arielle=
.Andrews@gov.bc.ca</a>&gt;; Pilchar, Molly CITZ:EX &lt;<a href=3D"mailto:Mo=
lly.Pilchar@gov.bc.ca" target=3D"_blank">Molly.Pilchar@gov.bc.ca</a>&gt;; S=
hutko, Craig CITZ:EX &lt;<a href=3D"mailto:Craig.Shutko@gov.bc.ca" target=
=3D"_blank">Craig.Shutko@gov.bc.ca</a>&gt;;
 Punnett, Alexander CITZ:EX &lt;<a href=3D"mailto:Alexander.Punnett@gov.bc.=
ca" target=3D"_blank">Alexander.Punnett@gov.bc.ca</a>&gt;; Morris, Matthew =
CITZ:EX &lt;<a href=3D"mailto:Matthew.Morris@gov.bc.ca" target=3D"_blank">M=
atthew.Morris@gov.bc.ca</a>&gt;<br>
<b>Subject:</b> Re: Process for dealing with VM issues</span><u></u><u></u>=
</p>
</div>
</div>
<p class=3D"MsoNormal">=C2=A0<u></u><u></u></p>
<div style=3D"border:1pt solid rgb(156,101,0);padding:2pt">
<p class=3D"MsoNormal" style=3D"line-height:12pt;background:coral">
<b><span style=3D"font-size:10pt;font-family:Verdana,sans-serif;color:gold"=
>[EXTERNAL]
</span></b><b><span style=3D"font-size:10pt;font-family:Verdana,sans-serif;=
color:navy">This email came from an external source. Only open attachments =
or links that you are expecting from a known sender.</span></b><u></u><u></=
u></p>
</div>
<p class=3D"MsoNormal">=C2=A0<u></u><u></u></p>
<div>
<div>
<p class=3D"MsoNormal">Hi Dave,
<u></u><u></u></p>
<div>
<p class=3D"MsoNormal">=C2=A0<u></u><u></u></p>
</div>
<div>
<p class=3D"MsoNormal">it&#39;s a typo I guess on the email. We were lookin=
g for a &quot;remote&quot; monitoring tool - web based, so that we can see =
resource utilization=C2=A0on the server without logging in. If we can
 get access to that tool specific to our servers , then it will be=C2=A0hel=
pful.<u></u><u></u></p>
</div>
</div>
<p class=3D"MsoNormal">=C2=A0<u></u><u></u></p>
<div>
<div>
<p class=3D"MsoNormal">On Thu, Jun 24, 2021 at 2:05 PM Smyth, David CITZ:EX=
 &lt;<a href=3D"mailto:David.Smyth@gov.bc.ca" target=3D"_blank">David.Smyth=
@gov.bc.ca</a>&gt; wrote:<u></u><u></u></p>
</div>
<blockquote style=3D"border-top:none;border-right:none;border-bottom:none;b=
order-left:1pt solid rgb(204,204,204);padding:0cm 0cm 0cm 6pt;margin:5pt 0c=
m 5pt 4.8pt">
<div>
<div>
<p class=3D"MsoNormal">Loren,<u></u><u></u></p>
<ul type=3D"disc">
<li class=3D"gmail-m_-5378725715241952683gmail-m-7255495689884880380gmail-m=
8981287957773122211msolistparagraph">
<span lang=3D"EN-US">Who is our contact person in case an issue arises that=
 we cannot solve ourselves?</span><u></u><u></u></li></ul>
<p class=3D"gmail-m_-5378725715241952683gmail-m-7255495689884880380gmail-m8=
981287957773122211msolistparagraph">
<span lang=3D"EN-US">The IMB is your escalation point, Matt and Alexander a=
nd myself. We can mediate your request to the vendor</span><u></u><u></u></=
p>
<p class=3D"gmail-m_-5378725715241952683gmail-m-7255495689884880380gmail-m8=
981287957773122211msolistparagraph">
<span lang=3D"EN-US">=C2=A0</span><u></u><u></u></p>
<ul type=3D"disc">
<li class=3D"gmail-m_-5378725715241952683gmail-m-7255495689884880380gmail-m=
8981287957773122211msolistparagraph">
<span lang=3D"EN-US">Is there any way to receive automated alerts if a serv=
er goes down?</span><u></u><u></u></li></ul>
<p class=3D"gmail-m_-5378725715241952683gmail-m-7255495689884880380gmail-m8=
981287957773122211msolistparagraph">
<span lang=3D"EN-US">The vendor has monitoring that alerts them only of out=
ages. If they detect a server is down they will investigate.
</span><u></u><u></u></p>
<p class=3D"gmail-m_-5378725715241952683gmail-m-7255495689884880380gmail-m8=
981287957773122211msolistparagraph">
<span lang=3D"EN-US">We have a central monitoring application called Nagios=
 for monitoring. It can alert us by email if we have outages or services wa=
rnings (ie low Disk space). We also can monitor services state changes as w=
ell. If you like we can add the Nagios
 client to the VM </span><u></u><u></u></p>
<p class=3D"gmail-m_-5378725715241952683gmail-m-7255495689884880380gmail-m8=
981287957773122211msolistparagraph">
<span lang=3D"EN-US">=C2=A0</span><u></u><u></u></p>
<ul type=3D"disc">
<li class=3D"gmail-m_-5378725715241952683gmail-m-7255495689884880380gmail-m=
8981287957773122211msolistparagraph">
<span lang=3D"EN-US">Is there an interface that we can login into for remov=
e monitoring?</span><u></u><u></u></li></ul>
<p class=3D"gmail-m_-5378725715241952683gmail-m-7255495689884880380gmail-m8=
981287957773122211msolistparagraph">
<span lang=3D"EN-US">The vendor monitoring is not possible to remove. Part =
of the contract.</span><u></u><u></u></p>
<p class=3D"MsoNormal">=C2=A0<u></u><u></u></p>
<p class=3D"MsoNormal">Also the vendor has an establish Sunday morning chan=
ge windows from 6-9am where they perform operational maintenance. Sometimes=
 it causes disruptions.
<u></u><u></u></p>
<p class=3D"MsoNormal">The vendor manages the security patching of the OS. =
They will schedule a date for patching and require approval by Matt or Alex=
ander to proceed.
<u></u><u></u></p>
<p class=3D"MsoNormal">Typically we stay out of the C: drive and install an=
y applications to other drives. The managing of small amount of working spa=
ce on the C drive we normally leave to the vendor.
<u></u><u></u></p>
<p class=3D"MsoNormal">=C2=A0<u></u><u></u></p>
<p class=3D"MsoNormal">Dave
<u></u><u></u></p>
<p class=3D"MsoNormal">=C2=A0<u></u><u></u></p>
<div>
<div style=3D"border-right:none;border-bottom:none;border-left:none;border-=
top:1pt solid rgb(225,225,225);padding:3pt 0cm 0cm">
<p class=3D"MsoNormal"><b><span lang=3D"EN-US">From:</span></b><span lang=
=3D"EN-US"> Mullane, Loren CITZ:EX &lt;<a href=3D"mailto:Loren.Mullane@gov.=
bc.ca" target=3D"_blank">Loren.Mullane@gov.bc.ca</a>&gt;
<br>
<b>Sent:</b> June 24, 2021 1:31 PM<br>
<b>To:</b> Smyth, David CITZ:EX &lt;<a href=3D"mailto:David.Smyth@gov.bc.ca=
" target=3D"_blank">David.Smyth@gov.bc.ca</a>&gt;<br>
<b>Cc:</b> Prodan, Matthew CITZ:EX &lt;<a href=3D"mailto:Matthew.Prodan@gov=
.bc.ca" target=3D"_blank">Matthew.Prodan@gov.bc.ca</a>&gt;; Andrews, Ariell=
e CITZ:EX &lt;<a href=3D"mailto:Arielle.Andrews@gov.bc.ca" target=3D"_blank=
">Arielle.Andrews@gov.bc.ca</a>&gt;; Abin Antony &lt;<a href=3D"mailto:abin=
.antony@aot-technologies.com" target=3D"_blank">abin.antony@aot-technologie=
s.com</a>&gt;;
 Pilchar, Molly CITZ:EX &lt;<a href=3D"mailto:Molly.Pilchar@gov.bc.ca" targ=
et=3D"_blank">Molly.Pilchar@gov.bc.ca</a>&gt;<br>
<b>Subject:</b> Process for dealing with VM issues</span><u></u><u></u></p>
</div>
</div>
<p class=3D"MsoNormal">=C2=A0<u></u><u></u></p>
<p class=3D"MsoNormal"><span lang=3D"EN-US">Hi David,</span><u></u><u></u><=
/p>
<p class=3D"MsoNormal"><span lang=3D"EN-US">=C2=A0</span><u></u><u></u></p>
<p class=3D"MsoNormal"><span lang=3D"EN-US">We had an access issue with the=
 VM this week, which your team was able to resolve in a timely fashion.<br>
<br>
A few questions for you if we need future support on the VM:</span><u></u><=
u></u></p>
<p class=3D"MsoNormal"><span lang=3D"EN-US">=C2=A0</span><u></u><u></u></p>
<ul type=3D"disc">
<li class=3D"gmail-m_-5378725715241952683gmail-m-7255495689884880380gmail-m=
8981287957773122211msolistparagraph">
<span lang=3D"EN-US">Who is our contact person in case an issue arises that=
 we cannot solve ourselves?</span><u></u><u></u></li><li class=3D"gmail-m_-=
5378725715241952683gmail-m-7255495689884880380gmail-m8981287957773122211mso=
listparagraph">
<span lang=3D"EN-US">Is there any way to receive automated alerts if a serv=
er goes down?</span><u></u><u></u></li><li class=3D"gmail-m_-53787257152419=
52683gmail-m-7255495689884880380gmail-m8981287957773122211msolistparagraph"=
>
<span lang=3D"EN-US">Is there an interface that we can login into for remov=
e monitoring?</span><u></u><u></u></li></ul>
<p class=3D"MsoNormal"><span lang=3D"EN-US">=C2=A0</span><u></u><u></u></p>
<p class=3D"MsoNormal"><span lang=3D"EN-US">Appreciate your insight here.</=
span><u></u><u></u></p>
<p class=3D"MsoNormal"><span lang=3D"EN-US">=C2=A0</span><u></u><u></u></p>
<p class=3D"MsoNormal"><span lang=3D"EN-US">Best,</span><u></u><u></u></p>
<p class=3D"MsoNormal"><span lang=3D"EN-US">=C2=A0</span><u></u><u></u></p>
<p class=3D"MsoNormal"><span lang=3D"EN-US">Loren</span><u></u><u></u></p>
<p class=3D"MsoNormal"><span lang=3D"EN-US">=C2=A0</span><u></u><u></u></p>
<p class=3D"MsoNormal"><span lang=3D"EN-US">=C2=A0</span><u></u><u></u></p>
</div>
</div>
</blockquote>
</div>
</div>
</div>
</div>
</blockquote>
</div>
</div>
</div>
</div>
</div>

</blockquote></div></div>

--00000000000064120c05c58b5f83--

**Comment by abin-aot** [comment]
Above one is the current active mail thread on this front, we are waiting for getting alerts set up. Also, asked for monitoring tool, if possible
