### ISSUE TITLE
Design integration for Formsflow.ai

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#145]
Title of ticket: 

#### Description
Determine technical considerations related to integrating formsflow with formsflow workflow (what stage of the product and how will we be utilizing formsflow.ai)

#### Dependencies
n/a

#### DOD
- [ ] Dev team to have a technical discussion and report back to wider team

**Comment by abin-aot** [comment]
COPY -PASTING @divyav-aot 's MOM of the technical discussion.

1.	WF will get initiated once the request is captured in the Line of Business(LOB) database. 
a.	Abin will be triggering a loosely coupled event once the data in captured in the database. This is workaround until we integrate with a queueing logic.
b.	Sumathi will initialize the WF in that event for now. Later it will get integrated with queueing logic.
c.	Currently Sumathi will call an aync call to initialize the WF before the event is ready.
2.	The request queue is a customized react component.
3.	Review request page may not be able to complete in this sprint due to the below concerns.
a.	Need analysis of the page, whether to use forms.io or react. Decision on the page design fully/partially in forms.io or react.
b.	Form submissions need to be captured in the LOB data.
c.	Need initial design of the WF ready.
d.	@loren.mullane@gov.bc.ca added a point to capture the comments, notifications, email, etc on the go for each request when we decide on the form design.
4.	If we are not able to complete review request story(#21) then will pickup filter request story(#82) for this sprint. We will consider #21 as an analysis task for this sprint.

**Comment by abin-aot** [comment]
As part of this an event/local async triggering based approach will be created . Along with task #20 API update

**Comment by sumathi-thirumani-aot** [comment]
[https://app.zenhub.com/files/358004325/2585ae67-08bd-46d5-a2e8-952ddd5cb8f3/download](https://app.zenhub.com/files/358004325/2585ae67-08bd-46d5-a2e8-952ddd5cb8f3/download)

This talks about the execution models and integration approaches available.
