### ISSUE TITLE
STRA related follow ups

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#151]
Explore available vendors for penetration scans

**Comment by mpilchar** [comment]
Please review - add comments or edit within cc: @lmullane @abin-aot @m-prodan @arielleandrews 

https://bcgov.sharepoint.com/:w:/r/teams/03521/Shared%20Documents/General/STRAs%20and%20PIAs/CITZ000816%20-%20FOI%20System%20-%20STRA%20Report%20v0.2.docx?d=wd353f147caf64842b49c92e7d923fb46&csf=1&web=1

**Comment by abin-aot** [comment]
@mpilchar @lmullane @m-prodan @arielleandrews  - Comments added into the doc on Teams, Main queries are here

1.  Are we adding File Conversion on the VM to this STRA, because this is NOT on openshift, its on separate VM ?
2. As per AXIS STRA, their services and url endpoints are available only inside BC GOV n/w and they didnt made it open to public internet. Considering that fact, why should we consider our FOI FLOW application to be wide open to internet? why cant we restrict this BC GOV network as AXIS, so that we can tighten the security ? 

3. Do we need to add a "access and availability" section on the STRA, similar to what AXIS STRA has? so that what ever decision(public/private to BC GOV) we take will be covered in the STRA
