### ISSUE TITLE
Suggestions on Advanced Search

### ISSUE THREAD

**Issue by sumathi-thirumani-aot** [bcgov/foi-flow#1530]
1) - [ ] Option to see the total number of search results.
2) - [x] Field "Search by Date Range" is very generic. It is Request Submitted Date or Due Date etc. 
3) - [x] System allows search without any data; the default selection of "Request Description" could be eliminated.
4) - [x] Flexibility to deselect the "Advanced Search" option like deselect on clicking again. [ Connected with above observation]
5) - [ ] Support for typeahead search in field "Public Body"
6) - [ ] Ability to see tags/search words regardless of what search filter button is selected (currently can only see the tags when "Request Details" button is selected
7) - [ ] Ability to clear search results

**Comment by sumathi-thirumani-aot** [comment]
Notification with data in given format will be sent by API via socket:
{'userid': 'foiintake@idir', 'idnumber': 'U-001', 'notificationid': 14, 'notification': 'zzzz', 'notificationtype': 'New User Comments', 'notificationusertype': 'Watcher', 'created_at': '2022 FEB 17 | 02:19 PM', 'createdby': 'suthirum@idir', 'requesttype': 'rawrequest', 'requestid': 1, 'foirequestid': 0, 'action': 'delete'}

**Comment by JHarrietha-AOT** [comment]
@lmullane @m-prodan @arielleandrews 

Just thought I would share my thoughts on these so we can either create tickets to update the feature or not

 Option to see the total number of search results.
•I don't think its necessary as user would know there is 10 results per page and can see the total numbers of pages at the bottom. And total numbers should be in reporting.

 Field "Search by Date Range" is very generic. It is Request Submitted Date or Due Date etc.
•We kept this simple on purpose due to the large about of date selections we see in existing IAO process and AXIS Screens. I think this is something we should wait until after the pilot launch to get feedback from users. It is something I know I want to ask once we have users in the system

 System allows search without any data; the default selection of "Request Description" could be eliminated.
• If this isn't difficult technically I think its a good change

 Flexibility to deselect the "Advanced Search" option like deselect on clicking again. [ Connected with above observation]
• I don't think this as necessary as it function like a tab more so, then the way filters should be functioning
 
Support for typeahead search in field "Public Body"
• Typeahead search always make things faster then scrolling, so like the idea. It would just need to support multi-selection in a easy to us way.

**Comment by m-prodan** [comment]
I think some people might like to see how many hits they get on a search, but you are right - seeing the total number of pages would be a good indicator too. Kind of like what you are saying for the second point, perhaps we should let our users tell us if this is necessary? 

And following that, I do agree with your second point Jackie - let's let the users tell us how data range should be handled. I agree there is a lot of dates to deal with as it is, so it will be interesting to hear what experiences uncover.

3+4 - agree with your perspective there Jackie - some type of descriptor or filter should be selected before you can search, and I like the tab design as it stands.

Typeahead - does that mean like autocomplete or auto-fill? If so, I think that's a good idea, but agree with the requirements you noted. I don't think we should prioritize for MVP but it could be a good nice to have in future development

**Comment by mpilchar** [comment]
I added 6) & 7) here after testing #1688 to keep suggestions for Advanced Search in one place

**Comment by KyEggleston** [comment]
Closing, as this ticket has already been addressed through subsequent tickets
