### ISSUE TITLE
ETL AXIS data for reporting

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#160]
Title of ticket: 

#### Description
This needs to be broken into many tasks.

#### Dependencies
Are there any dependencies?

#### DOD
- [ ] Setup data warehouse/design
- [ ] Identify columns for extraction
- [ ] Data modelling
- [ ] Setup nightly replication
- [ ] ETL design
- [ ] ETL

**Comment by abin-aot** [comment]
These are summarized list of points from the meeting from AXIS/ATIPExpress Team

1. API endpoints are very limited. By default they have only "create request" & "get status" endpoint.
2. Their team can expose/release the API endpoints in a customized way we need, but that comes with cost. but for this AXIS need to upgraded from 10.3 to 10.7. 
3. AXIS is an Application based of .NET & MS SQL Server. Backend can be reviewed and we can migrate data as required, but this need to analyzed.
4. Documentation part, I am not sure if they dont APIs then what level of documentation can be provided.

Personal Verdict : Options need to be discussed, in terms of moving ahead with AXIS in parallel, because "openFOI request" story have an existing dependency with it. if not, we might need to run both systems in parallel, which is cumbersome 

@lmullane @m-prodan @acoard-aot @divyav-aot @sumathi-thirumani-aot @JHarrietha-AOT @mpilchar @arielleandrews

**Comment by mpilchar** [comment]
Thanks for digging this one out of the icebox @lmullane

**Comment by mpilchar** [comment]
@abin-aot I think this task still needs to be broken into smaller tasks. Let me know if you or another team member can help break this down sometime next week? cc: @m-prodan

**Comment by abin-aot** [comment]
This has been breakdown to several  tasks, hence closing
