### ISSUE TITLE
Deployment Request Management to TEST

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#179]
Title of ticket: 

#### Description

1.  FormsFlow Deployment,  includes FOI Flow CustomWeb (FormsFlowWeb) & FOI - Custom WF
2.   Patroni LOB DB
3. Request Queue Management LOB API
4.  Redis Cluster - 

#### Dependencies
Are there any dependencies?
- **Image pulling issue on Openshift Service Agent. @acoard-aot  to reach out support**

#### DOD
- [ ]  Application will be available on TEST FOI Flow URL , with the functionalities demo'd on Sprint Dubrovnik
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by acoard-aot** [comment]
The API is currently deployed and functioning with a stock postgres DB. Imagepull issue currently persists for patroni only.  Perhaps Sumathi has different templates we can try?

**Comment by acoard-aot** [comment]
https://request-management-api-test.apps.silver.devops.gov.bc.ca/

Test API

**Comment by acoard-aot** [comment]
I am unassigning myself from this for now, as API is up and accepting requests.  If theres any further integration work in future I have (eg if any after formsflow?) I can be re-assigned/do the work then.

**Comment by acoard-aot** [comment]
Just discovered there is a dependency between these subtasks task (specifically item 3, the LOB API, and 4, Redis). I did not recall that latest versions of the api required redis.   There is also a depencency on getting the Angular app in front of Jackie to QA, as the Angular app needs the LOB API to be functioning.

I have gotten the LOB API done as much as possible, now I need Redis up in order to finish it.  @sumathi-thirumani-aot when working on the test environment if you could prioritize redis that would be appreciated, as it's blocking tasks for both you and me.  Thanks.

**Comment by sumathi-thirumani-aot** [comment]
Redis & Patroni is up and running in test region. 
Service name of redis: redis-formio
Service name of patroni:  patroni

**Comment by sumathi-thirumani-aot** [comment]
This requires setup & deployment of listed components

1. patroni : **Completed**
2. redis : **Completed**
3. forms-flow-bpm : 
4. forms-flow-web
5. forms-flow-forms: **Ongoing**

**Comment by sumathi-thirumani-aot** [comment]
**Use case (Steps):**
1. Submit FOI request using **client facing application replica test** url -> https://test.foirequestform.gov.bc.ca/ 
2. After successful submission; login to **new FOI Modernization Portal** using url -> https://test-foirequest.apps.silver.devops.gov.bc.ca/
Expected Behavior: The newly submitted request must be listed in home.
![image.png](https://images.zenhubusercontent.com/6081aecd755ce5720b249eb2/69ab6ea5-416e-4837-aa38-43dccefb1a89)
