### ISSUE TITLE
Login landing page no longer shows up

### ISSUE THREAD

**Issue by nkan-aot** [bcgov/foi-flow#1907]
Since url change, the below landing page no longer shows up, user goes directly to keycloak login

![image.png](https://images.zenhubusercontent.com/61b8d66efdea7284030f762c/ca899a58-7e6a-4510-83a6-44f8c557d54d)

Low impact, user is still able to login, just is not according to design

High - happens every time

**Steps to Reproduce**
make sure user is logged out, go to test or dev url 
https://dev.foirequests.gov.bc.ca
https://test.foirequests.gov.bc.ca

**Actual/ observed behaviour/ results**
user is directed to keycloak login

**Expected behaviour**
landing page should show

**Comment by m-prodan** [comment]
@nkan-aot - I've tested this, and it appears to be resolved... but for whatever reason, Microsoft Edge appears to still take me right to the keycloak login instead of the original landing/login page. Any thoughts as to why this is? No issues on chrome/firefox - behaviour is as expected, edge just keeps going right to keycloak. I confirm I am using https://test.foirequests.gov.bc.ca/ in edge

**Comment by m-prodan** [comment]
Actually - scratch that, I cleared my cache, and the behaviour is no longer happening in edge. May have been something related to that - we're good now @nkan-aot
