### ISSUE TITLE
Alert/Notification for failed ETL processes

### ISSUE THREAD

**Issue by richard-aot** [bcgov/foi-flow#2045]
When ETL packages fail to run, send an email alert/notification (if possible, also send a message to a Teams channel)

DoD

- [x] send an email if any ETL package fails to run

Update : Moved "Teams alert" DOD  to different ticket - see comments

**Comment by lmullane** [comment]
First step is to get SMTP from IMB.

**Comment by abin-aot** [comment]
![image.png](https://images.zenhubusercontent.com/607de5aafedfab08839427c4/65a1b226-f9ae-478f-8d5e-eab3f017ac3e)

Used BC GOV 's mail server ^^ to configure the DB Mail on TIKAL.DMZ - Prod. ETL server. As of now, its alerting my work email, But we can update that configuration with any common mailbox address. Please let me know, if any. @lmullane , @m-prodan

**Comment by abin-aot** [comment]
During stand up its decided to move alerts to  Teams channel as a separate ticket, since there is a coordination need to be done with team administrator at GOVT level - OCIO or Messaging team.  Idea is to set up an "FOI ALERTS" channel and map it with an email / common email - Where alerts are sent from different systems. 
cc: @lmullane  , @m-prodan

**Comment by abin-aot** [comment]
removing the Teams alert DOD and reducing estimate to 1
