### ISSUE TITLE
Meeting: Discuss consistent codes for client acronyms

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#211]
#### Description
Originated: During Sprint demo prep when Divya was demoing the review and edit request functionality. Ministry issue is related to the code which is there in FOI-Requests(Angular App) and FOI-FLOW. we used this file shared by Matt (IAO Client Acronyms.docx) for our master data. Here bc gov acronym is AFF and FOI-Requests(Angular App) has the code AGRI. So there is no matching code between FOI-Requests and FOI-Flow. That is why it was not selected in our Review Request page. Let's have a meeting to discuss

#### DOD
- [x] Meeting to determine what acronyms we will be using
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by abin-aot** [comment]
Plans has been made to use BCGOV code for IAO for the other organizations like Liquor Distribution Board etc. Also diff. in the code will be fixed in  FOI request app(Angular) till test env. and make it similar with all environments.  The change will go together into prod for all apps(FOI Flow, FOI requests etc.)

@divyav-aot @lmullane @m-prodan @acoard-aot @arielleandrews @JHarrietha-AOT @sumathi-thirumani-aot @mpilchar
