### ISSUE TITLE
Unable to persist Selection on Watchers for certain type of Request

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#2186]
**Describe the bug in current situation**
Go to this particular FOI Request, Unable to persists Watchers selection. This is submitted as a personal request and Sync with  AXIS , transitioned to "harms assessment". reproduction steps - TBA
https://test.foirequests.gov.bc.ca/foi/foirequests/539/ministryrequest/764

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Go to this particular request, https://test.foirequests.gov.bc.ca/foi/foirequests/539/ministryrequest/764
2. Click on Watcher list 
3. Try to select on user from Watcher list dropdown
4. Its not persisting the user

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by lmullane** [comment]
This is the Expected Behaviour.

GIVEN an IAO user has clicked the number of watchers
WHEN the dropdown opens
THEN only IAO team members should appear (i.e., no ministry users)

GIVEN a ministry coordinator has clicked the number of watchers
WHEN the dropdown opens
THEN only the ministry team member should appear (i.e., no IAO users)

Based on the above scenarios. This is fixed. 

Thanks. @richard-aot

**Comment by lmullane** [comment]
@nkan-aot, appears the watcher is covered by an automated functional test.

Please flag that we should update the automated test to reflect the Expected Behaviour above.

**Comment by nkan-aot** [comment]
sure, i will update tests to reflect the AC above

**Comment by lmullane** [comment]
Thanks, @nkan-aot. QA Master List had that as the expected behaviour so maybe covered already.

**Comment by nkan-aot** [comment]
just looked over the AC and automated tests again, it was not covered because I was only checking the correct IAO groups were present (i.e. flex or intake), not necessarily that ministry was NOT present. Also was testing the list at the Open stage so ministry users would not have shown up anyways. The ministry side is a separate test case so that is already covered. will update the tests to cover this case as well
