### ISSUE TITLE
Design - Non-Pilot Ministries Ability to Process Payments Online

### ISSUE THREAD

**Issue by JHarrietha-AOT** [bcgov/foi-flow#2293]
Title of ticket: Design - Non-Pilot Ministries Ability to Process Payments Online

#### Description
Design a flow, process and mock-ups of how we can on-board non-pilot users into the applicant fee payment process but nothing else.

#### Dependencies
Are there any dependencies?

#### DOD
- [ ] List the items that need to be complete for this ticket to be considered done
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by JHarrietha-AOT** [comment]
@m-prodan @arielleandrews @lmullane 
Links to update prototype: https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/941000374

Non-pilot users will land on a queue of there teams request that are in CFR be able to select or search for the request they want to process fees for. (Non-Pilot users have restricted search) When Non-Pilot users select a request they will be taken to the CFR forms. In the CFR Form they will be able to upload the Invoice and letter as well as insure the amounts pulled from AXIS are correct. Once they move through to the Approved Status, and have uploaded the documents on the form the "Email Applicant" button will become active.

Modal if Form hasn't been approved but user tries to move to next stages: https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/941000377
Modal if users hasnt upload documents but tries to move to next stages: https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/941000865
Modal if user tries to resend email: https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/941000866
Modal for sending emailing and having final confimation: https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/941000378

**Comment by lmullane** [comment]
Designs look good, Jacky.

A couple of questions:

- should we differentiate between the ministry (pilot vs non-pilot ministry) rather than the user? An IAO analyst may have some requests in the system that are pilot ministries and some that are not. So only in some instances will they only see the CFR form, correct?

- what would be the difference for the Advanced Search for non-pilot?

Sent from my iPhone

On Aug 8, 2022, at 8:53 AM, Jacklyn ***@***.***> wrote:

﻿

[EXTERNAL] This email came from an external source. Only open attachments or links that you are expecting from a known sender.


@m-prodan<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fm-prodan&data=05%7C01%7CLoren.Mullane%40gov.bc.ca%7C4307d8ff0b3a4f4e714b08da79561232%7C6fdb52003d0d4a8ab036d3685e359adc%7C0%7C0%7C637955707817286677%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=jt5lTt%2B7gHxHyxM9yqIupJpfonxJ%2BRw33hF50nmQSPc%3D&reserved=0> @arielleandrews<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Farielleandrews&data=05%7C01%7CLoren.Mullane%40gov.bc.ca%7C4307d8ff0b3a4f4e714b08da79561232%7C6fdb52003d0d4a8ab036d3685e359adc%7C0%7C0%7C637955707817286677%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3GZZrqc7obQ5qVeURmAvFAVKJC9E3uXcSricohr1zAQ%3D&reserved=0> @lmullane<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flmullane&data=05%7C01%7CLoren.Mullane%40gov.bc.ca%7C4307d8ff0b3a4f4e714b08da79561232%7C6fdb52003d0d4a8ab036d3685e359adc%7C0%7C0%7C637955707817286677%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Sy%2BqMt%2FWjRclKmi0zKcL8YQMoexN4lsjRurvee4VpoM%3D&reserved=0>
Links to update prototype: https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/941000374<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fjacklyn808742.invisionapp.com%2Fconsole%2Fshare%2F3W2O64AP5C%2F941000374&data=05%7C01%7CLoren.Mullane%40gov.bc.ca%7C4307d8ff0b3a4f4e714b08da79561232%7C6fdb52003d0d4a8ab036d3685e359adc%7C0%7C0%7C637955707817442887%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ZuugRp7VzXUtnvN7AoQMiLA8rSGA7wnWurQXfxviCpc%3D&reserved=0>

Non-pilot users will land on a queue of there teams request that are in CFR be able to select or search for the request they want to process fees for. (Non-Pilot users have restricted search) When Non-Pilot users select a request they will be taken to the CFR forms. In the CFR Form they will be able to upload the Invoice and letter as well as insure the amounts pulled from AXIS are correct. Once they move through to the Approved Status, and have uploaded the documents on the form the "Email Applicant" button will become active.

Modal if Form hasn't been approved but user tries to move to next stages: https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/941000377<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fjacklyn808742.invisionapp.com%2Fconsole%2Fshare%2F3W2O64AP5C%2F941000377&data=05%7C01%7CLoren.Mullane%40gov.bc.ca%7C4307d8ff0b3a4f4e714b08da79561232%7C6fdb52003d0d4a8ab036d3685e359adc%7C0%7C0%7C637955707817442887%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=k7%2Fx6Knk%2B4wkL9Vq%2BDjIdoVAlOVO9XNBfFt0xgXybNI%3D&reserved=0>
Modal if users hasnt upload documents but tries to move to next stages: https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/941000865<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fjacklyn808742.invisionapp.com%2Fconsole%2Fshare%2F3W2O64AP5C%2F941000865&data=05%7C01%7CLoren.Mullane%40gov.bc.ca%7C4307d8ff0b3a4f4e714b08da79561232%7C6fdb52003d0d4a8ab036d3685e359adc%7C0%7C0%7C637955707817442887%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=xwrIr%2FVTzaTuXJax6WtFcniEck2CBIP8lpGqzTwhuT8%3D&reserved=0>
Modal if user tries to resend email: https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/941000866<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fjacklyn808742.invisionapp.com%2Fconsole%2Fshare%2F3W2O64AP5C%2F941000866&data=05%7C01%7CLoren.Mullane%40gov.bc.ca%7C4307d8ff0b3a4f4e714b08da79561232%7C6fdb52003d0d4a8ab036d3685e359adc%7C0%7C0%7C637955707817442887%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3uu1ew4DRbpOmJ%2B3uAlHWjSmyf8SIvcuY7iOiO6Xo4c%3D&reserved=0>
Modal for sending emailing and having final confimation: https://jacklyn808742.invisionapp.com/console/share/3W2O64AP5C/941000378<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fjacklyn808742.invisionapp.com%2Fconsole%2Fshare%2F3W2O64AP5C%2F941000378&data=05%7C01%7CLoren.Mullane%40gov.bc.ca%7C4307d8ff0b3a4f4e714b08da79561232%7C6fdb52003d0d4a8ab036d3685e359adc%7C0%7C0%7C637955707817442887%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3qHiRafZHESffmltzaSbvpEw5heGXz9R%2BeS4Q1V8Ns8%3D&reserved=0>
