### ISSUE TITLE
Backups to S3 Object Storage

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#2794]
Title of ticket: 

#### Description
Move backups from OpenShift to S3/Object Storage.

If OpenShift goes down back ups are recoverable from S3/Object Storage.

Currently we have automatic backups but they are in OpenShift.

#### Dependencies
Are there any dependencies?

Assumption is that there is no custom integration work required. Revise estimate if this assumption is incorrect.

Full back is a manual push or a CHRON job to do an automatic push.

#### Further Task Breakdown

(Have left DoD untouched, but have been using this internally)

- [x] Python: Env value setup and configurable PersistentVolumeClaim file scanning
- [x] Python: Configured S3
- [x] Python: Dry-run uploading is totally working
- [x] Python: Upload file to Object Storage using boto3 - missing bucket
- [x] DevOps: Containerize into Dockerfile
- [x] DevOps: Deploy OpenShift Build yaml
- [x] DevOps: Deploy OpenShift deploy CronJob yaml
- [x] OpenShift: Change PVC Permissions, create new PVC, and swap over to use it
- [x] OpenShift: Share same PVC (read only?) as backup-container (see backup-deploy.yaml)
- [x] OpenShift: Create automated OpenShift Job to execute dockerfile

#### DOD
- [x] Verify whether we can push to S3 directly or if we need customization.
- [x] Configurable upload folder to S3, eg /dev/, /test/, /prod/ folders.  Right now all are just in main bucket.
- [x] After merge, revert buildconfig git branch
- [x] Backups automatically pushed to S3 storage

**Comment by acoard-aot** [comment]
Ran into issues last week and today.  I'm unable to directly mount the backup files in my upload script.  While OpenShift in general supports this, I didn't realize the type of StorageClass we're using on the BCGov OpenShift doesn't support this.  It only supports "ReadWriteOnce".  

We have options, but I want to discuss them with Abin and get some architectural review.

Some possible options:

1. Use SFTP upload.  The backups can be uploaded to SFTP.  I can then use my upload-to-s3 scripts to pull from the FTP server instead.  If we have access to an FTP server, great.  Alternative could be hosting a temporary (internal only) one in OpenShift.  If it's just pass-through, we can delete files from FTP after upload to S3 so shouldn't have to worry about significant storage.
2. Modify bcgov backup-container's volume mount type so that it's ReadWriteMany instead of ReadWriteOnce.  This should work, but because I'm modifying the bcgov file storage of backups I think it should require extra verifcation to ensure there's no introduction of corruption of backups.  There's also no guarantee this would work, but if it did work, is likely the "cleanest" solution.
3. Modify the bcgov backup-container to upload to s3.  This is us basically forking the backup scripts, adds a feature, and we could even potentially submit PR back to main repo.  


Open to all options, but so far #2 seems best unless we have a spare FTP server, then #1.  #2 will just take a few more days of verifying the backups work and is introducing some more risk.  There's also no guarantee #2 will work, whereas there is a guarantee #1 and #3 would work.

**Comment by acoard-aot** [comment]
This is done, merged into dev, and deployed to test and prod.

It's not deployed to dev as we run up against storage limits there.
