### ISSUE TITLE
Ministry Dashboard - TRA

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#3194]
Title of ticket: 

#### Description
Summarize issue 
Ministry reporting dashboard for TRA

Same dashboard filters as economy sector and Education with exceptions below:.

For reporting, TRA has requested they can report on the **Northern Region, South Coast Region** and the **Southern Interior Region** separately and as part of the stats for the **Highways & Regional Services Division.**

For reporting, TRA has requested they can report on **Corporate Writing Services** separately and as part of the stats for the **Strategic & Corporate Priorities Division.**

#### Dependencies
Are there any dependencies?

Divisional stages, #3191

#### DOD
- [x] Analyst Received and Performance Dashboard merged, with the following graphs
- [x] Average Days by Request States, 
- [x] Number of Processing Pages by Ministry, 
- [x] No Records Response by Ministry
and filters 
- [x] End FYr, End FQtr, By Month, By Week, 
- [x] Request Type (General, Personal), 
- [x] Request Status (Active, Overdue, Closed), 
- [x] Ministry Assigned To (i.e., coordinators)

**Comment by sumathi-thirumani-aot** [comment]
Technical Outcome
**Estimate - 5**

**Comment by lmullane** [comment]
@nkan-aot, we should discuss how to report down levels (i.e. region level and division level).

**Comment by m-prodan** [comment]
Dont close until PROD and there are divisions being pulled - do initial QA tests for performance metrics

**Comment by lmullane** [comment]
@abin-aot, can I confirm that the TRA's requests for reporting have been aggregated as per the ticket?

cc @KyEggleston

**Comment by abin-aot** [comment]
@lmullane  , @KyEggleston : As discussed earlier, The exceptions they indicated are already part of their/TRA's divisions and we have 'divisional' filters already.  Any update from that ?
![image.png](https://images.zenhubusercontent.com/607de5aafedfab08839427c4/867782e7-8502-4248-89e4-baeb42915de6)

**Comment by KyEggleston** [comment]
@abin-aot @lmullane: The divisions that show up under the 'Division' filter are correct - nothing to update there. 

However, when a TRAN user _**only**_ selects the Highways & Regional Services Division, the following divisions/regions should also be included in the results:

- Northern Region
- South Coast Region
- Southern Interior Region

This is because, organizationally, these three regions fall under the Highways & Regional Services Division. Therefore, they should automatically be added to the results if a user only selects the Highways & Regional Services Division. Rather than having to click four 'divisions' to filter by, they only need to select one to capture all the regions. 

![image](https://user-images.githubusercontent.com/117312323/214163098-10ae60ad-4c23-4ce1-a4a8-e12e199b8502.png)

The same goes for the Strategic & Corporate Priorities Division and Corporate Writing Services. If a user _**only**_ selects the Strategic & Corporate Priorities Division, it should also include the Corporate Writing Services as part of the results. This is because, organizationally, the Corporate Writing Services fall under the Strategic & Corporate Priorities Division. 

Therefore, rather than having to select both 'divisions', they only need to select the Strategic & Corporate Priorities Division to capture the results for both.

**Comment by abin-aot** [comment]
@KyEggleston : 'Automatic selection' is not supported by REDASH by default . I thought manual multi-select will work for them! - this is how all other filters work . Being said that, I can look into customizing filter specific to TRA, but that comes with an additional effort. cc: @lmullane

**Comment by KyEggleston** [comment]
Thanks @abin-aot for clarifying. 

Thoughts @lmullane @m-prodan?

**Comment by abin-aot** [comment]
Increasing estimate to 8 from 5, due to the changes with Divisions/sub divisions and fixing data mismatches

**Comment by KyEggleston** [comment]
@abin-aot - I just checked the updates. 

It looks like the search results are correct now. The same search results are being pulled if a user just selects Highways & Regional Services Division and when a user selects: 

- Highways & Regional Services Division
- Northern Region
- South Coast Region
- Southern Interior Region

The same goes for Strategic & Corporate Priorities Division and Corporate Writing Services (which is now an option). I believe this can be closed unless there is anything else to resolve that you noticed?
