### ISSUE TITLE
Tagging in Reply Comments (Ministry User)

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#3260]
**Describe the bug in current situation**
A Ministry User reported that their options for tagging in replies to comments are limited to their team only - they cannot tag someone else like another IAO user. Issue seems to be isolated to Ministry users only, IAO users are able to tag others outside of their team on reply comments.

NOTE: This bug does NOT impact new comments, Ministry users can tag IAO users with a new comment, it is only replies that are impacted. 

**Link bug to the User Story**
#787

**Impact of this bug**
Will require Ministry users to take extra steps/add new comments to tag IAO users, instead of being able to tag directly in replies. User group impacted: Ministry

**Chance of Occurring (high/medium/low/very low)**
High - easily replicated

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
1. Go to a request as a Ministry user and create a comment
2. Attempt to tag an IAO user in the reply comment

**Actual/ observed behaviour/ results**

**Expected behaviour**
See ticket #787 for full behaviour expected. Under assumptions, Ministry users are supposed to be able to tag any IAO user. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by aparna-aot** [comment]
**Regarding Production**: Currently in PROD, API caching is disabled because if new Keycloak users are added during working hours the cache won’t be updated and  these new users won’t be listed in the assignee list , comments tag list etc. in our FOI MOD app. But for this fix to work we need to enable caching in production.

**Solution for listing new Keycloak users in FOI MOD app** : For now, assignee lists has been removed from caching so whenever a new user is updated in Keycloak, assignee lists should show the updated users (Please TEST that scenario). But comment tagging might not show the updated list as its cached. So if Business team wants to see the updated user in the tag list for comments immediately, then the team can inform any of the developers so that they can call an API which will refresh the  keycloak user cache and the list will be updated. 
Also every morning around 5am PST the cached Keycloak users will be refreshed to ensure the list is up-to-date so if the team don’t want the user update to be reflected in the app(for Comment Tagging) as soon as its updated in Keycloak, then the nightly job will take care of it everyday.

**To Do**: Later on when the admin screens are setup, we will provide a link/button from that dashboard so that whenever the Business team updates any users and want to see the change immediately they can just click that button from dashboard & all the updates will be reflected in our app.

**Comment by KyEggleston** [comment]
@aparna-aot - Tested whenever a new user is updated in Keycloak, that the assignee lists should show the updated users.
