### ISSUE TITLE
Remap and Update to Team Names for IAO's Re-Alignment

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#3499]
Title of ticket: 
Remap and Update to Team Names for IAO's Re-Alignment

#### Description
IAO will be re-aligning which Ministries report to certain teams, and are updating the names of teams. This ticket is to help prepare for that change in FOI Mod

Note - there will be a separate ticket for updates to request assignments rules and processes

#### DOD
- [ ] Update Central/Business Team Name to Central and Economy Team
- [ ] Following Ministries will be mapped as default for reporting to Central and Economy team: OOP, PSA, FIN, TRA, TIC, GCP, JED/JER, MMA, LBR, TAC, CTZ, CAS, LDB, OBC, MGC
- [ ] Amalgamate Justice Health and Resource team to: Resource and Justice Team
- [ ] Following Ministries will be mapped as a default for reporting to the Resource and Justice Team: FOR, EML, PSS, COR, EMC, MAG, OCC, HSG, IIO, MOE, EAO, WLR
- [ ] Update Social Education team to Community and Health Team
- [ ] Following Ministries will be mapped as default to Community and Health Team: MSD, CLB, PSE, HTH, MHA, IRR, DAS, AGR
- [ ] Update MCFD Personals Team to Children and Family Team
- [ ] Following Ministries will be mapped to this team - CFD
- [ ] Add new team - Children and Education Team
- [ ] Following ministries will be mapped to Children and Education Team: ECC/EDU (see note below re: CFD)
- [ ] Add new team - Coordinated Response Unit

**Comment by m-prodan** [comment]
As discussed - this will be a higher priority than the comment reply story

**Comment by m-prodan** [comment]
Also discussed - @richard-aot will join Nick on this task after his bug ticket completes

**Comment by nkan-aot** [comment]
@m-prodan just want to clarify, I see CFD mapped under both "Children and Family Team" and "Children and Education Team". Is "Children and Family Team" only taking personal CFD requests and "Children and Education" taking general CFD requests?

**Comment by m-prodan** [comment]
new user groups and members can be found in this document: https://bcgov.sharepoint.com/:x:/t/03521/EV1fKDoOyrNJkxmA93Oosp0Be2ussi1MDrioNige-rFzNA?e=IFTkAY

**Comment by nkan-aot** [comment]
notes for QA: I have added the groups in test. I have also added the following test users in each group
Central and Economy Team: foibusiness2@idir, foicentral2@idir
Resource and Justice Team: foijustice2@idir
Community and Health Team: foisocialtech2@idir
Children and Family Team: foimcfd2@idir foichildrenfamily1@idir
Children and Education Team: foichildreneducation1@idir
Coordinated Response Team: foicoord1@idir

**Comment by liseandtea** [comment]
General and personal files are going to the proper queues/watcher alert menu with the following exceptions:
JER General defaults to the old Central Team
JER Personal defaults to the Flex Team

**Comment by m-prodan** [comment]
@liseandtea - thanks for doing this!

I think we are OK with the JER issue. I just did a double check in AXIS - the only open requests now are JED requests, all of the old JER requests are now closed. We won't get anymore JER requests, so I think that is fine as is. Probably good to close this ticket now!

**Comment by liseandtea** [comment]
@nkan-aot Hey! I am moving this back to review for one small adjustment. 

EDU General defaults to the Social Education Team.
EDU Personal defaults to the Flex Team.
This will have an impact on the 2 open FOI requests and 7 OIPC reviews open in AXIS.

Both EDU personal and general should default to the Children and Education team.

**Comment by nkan-aot** [comment]
@liseandtea commenting here so @m-prodan can see as well.
Are any of the current requests in AXIS before open state? Basically the mapping only affects the assignment from "intake in progress" to "open", after that point once it has been assigned to an individual it stays with that individual unless manually changed. So assuming all new requests should be coming in with ECC will this be a non issue? 

Current implementation is that any existing requests will continue to remain with the old business groups, and we will keep people as members of both groups until all existing requests for that group have been closed. However this should not be noticeable to users anyways since by open or CFR state it should be assigned to an individual and remain with that individual, and that individual will be part of both the old and new business group. 

Also would like to note that with #3500 all IAO users are available in the dropdown so requests can be assigned across business groups.

Also just to clarify, all general requests are still going to Flex Team correct?

**Comment by liseandtea** [comment]
@nkan-aot Thanks Nick! Matt and I chatted and are okay to close this ticket and #3500. Since there are only 2 requests, one of which should be closed soon, the impact is low. Also they are assigned to the same analyst so once we change the KC accesses there will only be one name listed under Social Education. We were worried about having duplicate lists and things getting assigned to the wrong one.

**Comment by liseandtea** [comment]
@nkan-aot Thanks Nick! Matt and I chatted and are okay to close this ticket and #3500. Since there are only 2 requests, one of which should be closed soon, the impact is low. Also they are assigned to the same analyst so once we change the KC accesses there will only be one name listed under Social Education. We were worried about having duplicate lists and things getting assigned to the wrong one.

**Comment by liseandtea** [comment]
@m-prodan closing request as discussed!
