### ISSUE TITLE
.PPT to PDF File Conversion or Incompatible File

### ISSUE THREAD

**Issue by KyEggleston** [bcgov/foi-flow#3664]
#### Description
From feedback at the Gathering Records training, we need to be able to upload .PPT files to the Gathering Records log, and they must be either converted to PDF, or uploaded as incompatible files.  

#### Dependencies
Are there any dependencies?

#### DOD
- [ ] PPT converts to PDF and includes notes
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by KyEggleston** [comment]
@lmullane @m-prodan @liseandtea - Creating this to capture what was brought up at training before I leave. Currently we don't accept .PPT files in the Gathering Records log. 

![image](https://user-images.githubusercontent.com/117312323/232914180-9849bb36-ebc4-4afc-80a1-730bb05e88b6.png)

**Comment by lmullane** [comment]
Thanks, @KyEggleston. Agree it is high priority.

**Comment by KyEggleston** [comment]
Additional note for refinement - users said if the file is converted to PDF, they need to be able to see the speaker / slides notes

**Comment by lmullane** [comment]
Business to QA and decide if there is an acceptable number of conversions. 

The issue right now is that not all charts are converted nicely. If there is a conversion issue with charts, the user will need to replace with a manually converted PDF of the deck.

Will also need to remove PPT from the incompatible files; config change.

**Comment by nkan-aot** [comment]
@KyEggleston this is due to a hardcoding file format issue in marshal. As part of #3915 I have moved that to a configuration but it is not in marshal yet. I have just added pptx to the list of formats for now. 

As for error files, I believe even other file types with conversion errors have the original file being included in the harms package. I think this is so they can easily convert it outside without having to download that file separately again. (see behaviour in https://dev.foirequests.gov.bc.ca/foi/ministryreview/26/ministryrequest/26) If this is not the case can you create a separate bug ticket for that? Since it is not unique to pptx.

Otherwise please check again and make sure pptx are being included in the harms package properly now.

**Comment by KyEggleston** [comment]
pptx are being uploaded fine (aside from pptx with certain charts), but can be replaced manually, and when they are replaced manually the harms package is updated accordingly. Harms package appears fine.

**Comment by abin-aot** [comment]
Just to give a heads up that only .ppt**X** can be converted this time to PDF.  .ppt will still remain as incompactible - I am commenting that on #3664 . I am sure @nkan-aot  have given this update! but thought to repeat again
