### ISSUE TITLE
PROD - .MSG files throwing errors - root cause unknown 

### ISSUE THREAD

**Issue by KyEggleston** [bcgov/foi-flow#3885]
**Describe the bug in current situation**
In production, .MSG files are throwing errors when they are not expected to. The emails and attachments are not encrypted, and they contain a variety of different file types. Retry did not resolve the issue. Some are marked as confidential via Outlook, but this does not appear to be the cause. See PSA-2023-31668 for example.

**Link bug to the User Story**

**Impact of this bug**
High

**Chance of Occurring (high/medium/low/very low)**
High

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by KyEggleston** [comment]
@abin-aot @lmullane @m-prodan @liseandtea - high priority, as it impacts harms and getting package ready for redaction. Workaround is manually merge email and attachments into a PDF, and reupload / manually replace, but time consuming for large packages.

**Comment by lmullane** [comment]
Thanks for flagging, @KyEggleston

Do we know how many requests packages have been impacted?

**Comment by KyEggleston** [comment]
Three so far, two of which were only one file (which could easily be resolved by saving the email and attachments as individual PDFs and merging them), but the request above has 20+ in error, and has enough volume to perhaps find a root cause.

**Comment by lmullane** [comment]
Thanks for the additional info, Kyle.

**Comment by lmullane** [comment]
@m-prodan as discussed, please review prod requests to see if there is any commonalities and report back.

**Comment by m-prodan** [comment]
FYI @aparna-aot - I spoke with an IAO analyst about the file PSA-2023-31668.

They wanted to see what would happen if they downloaded for harms, and what they got was interesting. All of the error email files downloaded in their original file format, as well as the consolidated PDF of the successful conversions. I seemed to recall that error files do not get included in the harms download, which is why users need to fix them first. 

Not sure if this helps, but I thought the additional information might help narrow down the issue.

**Comment by KyEggleston** [comment]
Confirmed working now - resolving ticket.
