### ISSUE TITLE
Records Log - Harms Package - Attachment Sort

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#3888]
* As a Ministry/IAO User
* I want to keep the attachments (child) with the main email file (parent)
* so that the order of my package makes more logical sense

**Assumptions & Scope**	
User feedback from the harms download revealed a gap in our initial testing/business requirements around how harms packages should be compiled.

Right now, our stitch/sort order logic is from modified date, and this includes every single file with no consideration to its status as a child to a parent file (eg. attachment/embed to an email). This creates confusion and is requiring users to manually update packages.

Users have reported that child files should be included with the parent file as part of the sort order, and not strictly moved by the modified date (eg - attachments to an email should follow immediately after the email in the consolidated PDF package, instead of by their sort date)

To give a basic illustration:
Take these 3 files
File X - date modified thursday
File Y - date modified tuesday
File Z - Date modified wednesday
Attachment A to file Z- Date modified Monday
Attachment B to file Z - Date modified wednesday

Sort order should be:
File Y
File Z
Attachment A
Attachment B
File X

What is IN scope?
Update to stitching logic

**Acceptance Criteria**	

**Scenario 1: Download Harms PDF by with a Division in progress**
* GIVEN the system complete creating the harms PDFs
* WHEN ministry coordinator or IAO user clicks "Download Harms PDF" again
* THEN PDF(s) will be exported in one consolidated, linear PDF for each Division organized by modified date of each PARENT file
* AND CHILD files will be sorted to follow their associated parent file, sorted by modified date
* AND the consolidated PDF(s) for each Division will be include in the ZIP file
* AND no individual PDF(s) will be included in the ZIP file (only PDFs consolidated by Division)
* AND the file name will be with following format: Request ID - Harms - Division (see comments below for eg)
* AND the ZIP file will be downloaded onto the user's computer

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by m-prodan** [comment]
@lmullane @KyEggleston @abin-aot @liseandtea @divyav-aot - to be discussed as emergency fix at stand up tomorrow on friday.

I took the original download for harms story, and updated the scenarios to capture the missed requirements around how attachments should be sorted. I drew up an example in assumptions to better illustrate what we need (I hope!)

**Comment by lmullane** [comment]
@m-prodan, we will need a 2 additional stories:

1. For marking that page(s) are attachments in the Harms Package
2. Records Review app will also organize attachments after the parent record.

**Comment by nimya-aot** [comment]
I noticed that there are some scenarios like records have attachments and those attachments have attachments inside. we are marking it as duplicate on those situations as parent has same attachments. so discussed with  @m-prodan and concluded that since its an edge case we are  keeping as it is( So all the attachments of  child message file will be there in the records package with respect to  the modified date sort order instead of placing right after its parent )

![image.png](https://images.zenhubusercontent.com/63e6c81be9adb8e6f876c7e0/d511342e-251b-4892-b8f8-272a9cef1aa2)
![image.png](https://images.zenhubusercontent.com/63e6c81be9adb8e6f876c7e0/4774065b-1e51-48f0-aff0-e865b5e5806c)
![image.png](https://images.zenhubusercontent.com/63e6c81be9adb8e6f876c7e0/53088cc4-5545-4e6b-8cd2-0b9f15be9d4c)

**Comment by divyav-aot** [comment]
Increasing the effort as an unexpected issue related to lastModifiedDate has been identified.

The issue is related to specific browsers like Firefox. We are taking lastModifiedDate property of the File object and saving the same to DB. But, different browsers have implemented different versions of the File API, and the lastModifiedDate property was not included in all of them. Meaning, some browsers may not have "lastModifiedDate " property at all.  Due to this, the files uploaded using Firefox browser is missing this lastModifiedDate property. 

So, Instead of using the lastModifiedDate property, I have updated to use the lastModified property, which represents the last modified timestamp of the file.

screenshot of Firefox File object.
![image.png](https://images.zenhubusercontent.com/6081a4273965c56c02fdc82c/0970276c-690a-4929-8a15-c90bfaf800b7)
screenshot of Edge/Chrome File object
![image.png](https://images.zenhubusercontent.com/6081a4273965c56c02fdc82c/8c55bf5e-7624-4aea-866f-55377b7824b0)

**Comment by nimya-aot** [comment]
One thing noticed regarding the sort order , when we upload a message file and if it has any child message file (which has attachments) then modified date of child message file changes(it wont be the same as its original modified date as modified date changes while attaching to a message ) @m-prodan

**Comment by divyav-aot** [comment]
@m-prodan, @nimya-aot is referring to below sample. Here top parent is MSG1.msg(01/03/2023). Its attachments are att_MSG0nMSG1.msg(01/01/2020), MAIN_PARENTATT.pdf(01/02/2021). Since att_MSG0nMSG1.msg got attached to MSG1.msg on 01/03/2023, the modified date of att_MSG0nMSG1.msg changes to 01/03/2023. Due to this the sort order in Harms will get changed based on the new modified date. But, in any case the relationship between the parent and child remains. 
![image.png](https://images.zenhubusercontent.com/6081a4273965c56c02fdc82c/56b16e22-171b-45c0-84c4-2662f319a6a0)

**Comment by abin-aot** [comment]
Based on conversation with @lmullane and @m-prodan , with sample MSG files attached here, it was demonstrated that the attachment files on EMAIL (MSG FILE) **always follows** the PARENT MSG file content on PDF stitched output. The minor discrepancy with the SORT order by `modified date` inside the PARENT MSG will not be a problem as agreed by the business, since attachments are always following the PARENT message file, hence `continuity and context ` of the attachments are `PRESERVED` on the stitched file. cc: @nimya-aot , @divyav-aot , @nkan-aot  

 [https://app.zenhub.com/files/358004325/79bcf150-67c7-4991-bef3-65cf5375efbd/download](https://app.zenhub.com/files/358004325/79bcf150-67c7-4991-bef3-65cf5375efbd/download)

**Comment by m-prodan** [comment]
My own tests are looking good - between that and what @abin-aot has demonstrated, I am confident in the fix. Great job team @divyav-aot @nimya-aot @abin-aot
