### ISSUE TITLE
Discrepancy between Gathering Records and File Watcher conversion

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#3910]
**Describe the bug in current situation**

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 
Excel cannot be redacted or reviewed 
**Chance of Occurring (high/medium/low/very low)**
Unknown
**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**
2. Click on the converted PDF
3. Download the converted PDF

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

Given an Excel is uploaded into Gathering Records
When it is converted to PDF(s)
Then the PDFs should be readable and follow the same conversion logic as file watcher

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by lmullane** [comment]
As discussed, we need to have all columns on the page, but we can have all Excel tabs in one PDF rather then creating one PDF per tab as File Watcher does.

cc @abin-aot cc @m-prodan

**Comment by abin-aot** [comment]
@lmullane , @m-prodan : This issue is fixed , issue was related with version we were using on Synfusion, it was a year latest from FileWatcher's Syncfusion version - but we cant downgrade to that old version, hence upgraded to the latest Syncfusion version and matched the conversion quality of provided excel and looks exactly same. Also tested other conversions - looks good!

**Comment by lmullane** [comment]
@abin-aot, we have validated that the fix is done. Thanks for the quick work. We can go to Prod EOD.

cc @m-prodan  , @nimya-aot
