### ISSUE TITLE
Setup GitHub Actions

### ISSUE THREAD

**Issue by lmullane** [bcgov/foi-flow#41]
DOD:

Dependency:

Need code to automate.

**Comment by acoard-aot** [comment]
Hey @lmullane - I'll need to be granted additional access to the repo to set this up.  I believe I'll need admin access. Right now if I go into Settings, I just see 2 options (rather than like the ~10 if you have admin), and importantly Actions is missing.


https://github.com/bcgov/foi-flow/settings

**Comment by lmullane** [comment]
Hey @acoard-aot, I've granted you admin access for this repo, and will do so for our other 2 repos as well.

**Comment by acoard-aot** [comment]
Great, thanks.  Confirmed I have access, and actions are enabled, so we're good to mark this done.
