### ISSUE TITLE
Single Source of Truth - Divisions

### ISSUE THREAD

**Issue by abin-aot** [bcgov/foi-flow#4183]
Title of ticket: 

#### Description
This task has been created to Remove existing `Program Area Divisions ` Tables and related dependencies like `PROGRAM AREAS ?? `  inside DOC Reviewer DB , in order to keep single source of truth of Divisions across FOI FLOW app. At present DOC REVIEWER Web App (only?) using this table(s)

#### Dependencies
Are there any dependencies?

#### DOD
- [x] Analyze the repercussions of removing Divisions, Program areas from Doc Reviewer DB - On initial analysis, its only used  for Left panel on Doc Reviewer Web app, so Idea is to Create a new endpoint for Divisions by  Program area from FOI FLOW
- [x]  Once above Analyze DOD is over and correct, Develop an API endpoint or use/check existing APIs for Divisions
- [x]  Update Left Panel Front End component to use FOI FLOW API endpoint for divisions.
- [x]  Integration test
- [ ]

**Comment by abin-aot** [comment]
@nkan-aot , @divyav-aot , @richard-aot , @aparna-aot , @sumathi-thirumani-aot  - Update / Add DODs, if required

**Comment by m-prodan** [comment]
Question on this - and one we may need to talk about at stand up tomorrow. How should we best QA this? I think this is the one where we want newly added or removed divisions to display properly in the redaction app - is that right?

cc  @Aman-Hundal @sumathi-thirumani-aot @nkan-aot @divyav-aot @aparna-aot @richard-aot

**Comment by m-prodan** [comment]
Note: to QA, add a division to an existing Ministry and confirm the records can be uploaded to doc reviewer and page flags can be added/changed

**Comment by m-prodan** [comment]
Hey Team - after doing some more testing, I've run into what seems like some more errors. I can see for sure that adding a new division is allowing records to be displayed in the redaction app; however, when I switch the filter to division, it greys everything out. Oddly enough, I can select the same records when sorting by modified date. I am unsure if this is because of some larger issue in the test doc-reviewer or not. Here are some screenshots - let me know what you think @Aman-Hundal 

cc @divyav-aot @abin-aot @nkan-aot [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaGlMIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--67f42dafc29671e5a8e607d955e6f06bfd928cf7/error%20screenshot%201.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaG1MIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5d1254a8b2c668f24687aa67b5b538e81880a3c1/error%20screenshot%202.png)

**Comment by m-prodan** [comment]
Working as expected now - adding new divisions and uploading records now show in the doc reviewer.

**Comment by m-prodan** [comment]
possible bug introduced, see #4426

**Comment by Aman-Hundal** [comment]
Follow up, confirmed that bug is not related to ticket 4183. This ticket can be closed.
