### ISSUE TITLE
Team training on QA manual testing

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#43]
Description
Training with team members on approach and plan for testing and release planning

DOD
QA testing
Release planning

**Comment by mpilchar** [comment]
@JHarrietha-AOT are you comfortable leading us through this tomorrow?

**Comment by JHarrietha-AOT** [comment]
@mpilchar Happy to lead it, I am planning on working on a doc today so we have one place to record what has been tested, and what the results are, along with QA best practices. Because I have been working on setting up with doc I would like to increase the estimate to include that task for myself. And likely need to de-prioritize something else from this sprint.

**Comment by m-prodan** [comment]
Closing this ticket per our meeting this morning
