### ISSUE TITLE
Standardize Responsiveness of Left Hand Nav Panel

### ISSUE THREAD

**Issue by m-prodan** [bcgov/foi-flow#4413]
* As an IAO user
* I want the left hand nav panel to be responsive to my activities in the working panel
* so that I can more quickly update page flags

**Assumptions & Scope**	
User Feedback from the super users session - it was indicated that having the left hand nav standardize with the working/viewing panel would be very helpful to quickly apply flags as needed.

Right now, clicking on a page in the left hand nav panel will update the viewing panel. Users have indicated that clicking or taking actions within the viewing panel should automatically select the corresponding page in the left hand nav panel.

What is IN scope?

What is NOT in scope?

**Acceptance Criteria**	

**Scenario 1: Clicking in Viewing Area**
* GIVEN an IAO user is scrolling through a package of records in the review app
* WHEN they click on the viewing/editing area
* THEN the corresponding page in the left hand nav will be selected as well

**Dependencies? What is the impact of this dependency? (If so, link dependency in the ticket, make it visible in a team´s backlog)**

**Validation Rules? (If yes, list here)**	

**Design**
@xxx - please link the Design here

**Definition of Ready**

1. [ ] Is there a well articulated User Story?
2. [ ] Is there Acceptance Criteria that covers all scenarios (happy/sad paths)?
3. [ ] If there is a user interface, is there a design? 
4. [ ] Does the user story need user research/validation?
5. [ ] Does this User Story needs stakeholder approval?
6. [ ] Design / Solution accepted by Product Owner
7. [ ] Is this user story small enough to be completed in a Sprint? Should it be split?
8. [ ] Are the dependencies known/ understood? (technical, business, regulatory/policy)
9. [ ] Has the story been estimated?

**Definition of Done**

1.    [ ] Passes developer unit tests
2.    [ ] Passes peer code review
3.    [ ] If there's a user interface, passes UX assurance
4.    [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
5.	[ ] Confirm Test cases built and succeeding 
6.	[ ] No regression test failures
7.	[ ] Test coverage acceptable by Product Owner
8.	[ ] Ticket ready to be merged to master or story branch
9.	[ ] Developer to list Config changes/ Update documents and designs
10.	[ ] Can be demoed in Sprint Review 
11.	[ ] Tagged as part of a Release
12.   [ ] Feature flagged if required
13.  [ ] Change Management activities done?

**Comment by abin-aot** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaUsrIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--87dc40ffd3afe8bf8cd0ebcb61d3ec3cf75fc52a/image.png)

**Comment by divyav-aot** [comment]
there is an auto scroll happening when I add redaction to a page. This happens only if the request has less no of pages. 
You can reproduce the issue here. https://dev-reviewer-web.apps.silver.devops.gov.bc.ca/foi/13919
Steps: 
click on Expand all button from left panel.
start scrolling the pages from middle pane and try to draw a redaction box in page 5.
 you can see issue.
another issue: the total page count is not matching in the left panel.
cc. @nkan-aot
@nimya-aot  - make sure to test this scenario when this ticket is moved to test environment. 
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2dOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6bf5c5865cbe2c95caa9eb61b3825078a5cf393b/Autoscroll%20issue.mp4)

**Comment by nimya-aot** [comment]
working as expected, so closing
