### ISSUE TITLE
8.3.3 - Small Feature Update (Help and Attachment Updates)

### ISSUE THREAD

**Issue by divyav-aot** [bcgov/foi-flow#4475]
**Place-in the release name**
8.3.3 - Small Feature Update (Help and Attachment Updates)
1. Help Icon/Button - https://app.zenhub.com/workspaces/foi-flow-607f0ab6ae54b700111dc733/issues/gh/bcgov/foi-flow/4246
2. Attachments - Reclassify File Tag- https://app.zenhub.com/workspaces/foi-flow-607f0ab6ae54b700111dc733/issues/gh/bcgov/foi-flow/3398
3. Delete Division Validation for Records Tagging - https://app.zenhub.com/workspaces/foi-flow-607f0ab6ae54b700111dc733/issues/gh/bcgov/foi-flow/4184
4. Attachments - Retain Original Upload Date- https://app.zenhub.com/workspaces/foi-flow-607f0ab6ae54b700111dc733/issues/gh/bcgov/foi-flow/4200
5. RequestDocuments' updated_at attribute being updated for all previous versions - https://app.zenhub.com/workspaces/foi-flow-607f0ab6ae54b700111dc733/issues/gh/bcgov/foi-flow/4366
6. Attachments - Applicant Tag - Personal Requests - https://app.zenhub.com/workspaces/foi-flow-607f0ab6ae54b700111dc733/issues/gh/bcgov/foi-flow/4333
7. Single Source of Truth - Divisions - https://app.zenhub.com/workspaces/foi-flow-607f0ab6ae54b700111dc733/issues/gh/bcgov/foi-flow/4183
8. TEST - Divisions not Available - HSG - https://app.zenhub.com/workspaces/foi-flow-607f0ab6ae54b700111dc733/issues/gh/bcgov/foi-flow/4426
9. Download for Harms - Inactive while documents processing - https://app.zenhub.com/workspaces/foi-flow-607f0ab6ae54b700111dc733/issues/gh/bcgov/foi-flow/3903
10. Records - Cleanup - https://app.zenhub.com/workspaces/foi-flow-607f0ab6ae54b700111dc733/issues/gh/bcgov/foi-flow/4268

This release has changes to FOI-FLOW FE and BE, Doc reviewer BE

#### Activity start time
Summarize issue 

#### Activity end time
Summarize issue 

#### Step-1: Database Backup (Check the desired components)
Capture the backup details 
- [x] FOI DB (xxx)
- [x] BPM DB
- [x] Docreviewer DB

#### Step-2: Image Backup (Check the desired components)
Capture the image details 
- [x] request-management-api (yyy)
- [x] forms-flow-web
- [ ] notification-manager
- [x] reviewer-api
- [ ] reviewer-web
- [ ] reviewer-conversion
- [ ] reviewer-conversion-largefiles
- [ ] reviewer-dedupe
- [ ] reviewer-dedupe-largefiles
- [ ] reviewer-pdfstitch
- [ ] reviewer-pdfstitch-largefiles

#### Step-3: Production - Tagging of image (Check the desired components)
- [x] request-management-api
- [x] forms-flow-web
- [ ] notification-manager
- [x] reviewer-api
- [ ] reviewer-web
- [ ] reviewer-conversion
- [ ] reviewer-conversion-largefiles
- [ ] reviewer-dedupe
- [ ] reviewer-dedupe-largefiles
- [ ] reviewer-pdfstitch
- [ ] reviewer-pdfstitch-largefiles

#### Step-4: Signoff from business
- [x] Yes
- [ ] No
- [ ] Not Applicable

#### Step-5: Healthcheck (Check the desired components)
- [x] FOI DB
- [ ] BPM DB
- [x] Docreviewer DB
- [ ] redis-
- [ ] redis-
- [ ] redis-
- [x] request-management-api
- [x] forms-flow-web
- [ ] notification-manager
- [x] reviewer-api
- [ ] reviewer-web
- [ ] reviewer-conversion
- [ ] reviewer-conversion-largefiles
- [ ] reviewer-dedupe
- [ ] reviewer-dedupe-largefiles
- [ ] reviewer-pdfstitch
- [ ] reviewer-pdfstitch-largefiles

#### Step-6: Staging - Tagging of image (Check the desired components)
- [ ] request-management-api
- [ ] forms-flow-web
- [ ] notification-manager
- [ ] reviewer-api
- [ ] reviewer-web
- [ ] reviewer-conversion
- [ ] reviewer-conversion-largefiles
- [ ] reviewer-dedupe
- [ ] reviewer-dedupe-largefiles
- [ ] reviewer-pdfstitch
- [ ] reviewer-pdfstitch-largefiles

**Observations**
List down the observations of incidents which happened in release window

**Overall Rating**
- [x] Good (No change)
- [ ] OK (With observations)
- [ ] Bad(Rollback)

**Comment by divyav-aot** [comment]
@Aman-Hundal  - please confirm if there is any changes need to be pushed for docreviewer BE (related to single source of truth - divisions)

**Comment by Aman-Hundal** [comment]
Hey all,

Can confirm that there were changes to docreviewer BE for 4183

**Comment by abin-aot** [comment]
a) Login to OCP Silver console, navigate to the d7abee-prod project namespace
b) find the workload/container "foi-bkup" and navigate to its pod's terminal.
c) Just do an "ls" to see the file listed and make sure "backup.sh" exists
d) if yes, execute the file ./backup.sh with -1 parameter. Say like, ./backup.sh -1
e) the above command will take DB back ups of FOI FLOW DB and BPM

2) Back ups of Container Images 
-- ---- --- -- --- --- ----- --

a) On the local CLI tool (RUN CMD), login to BC GOV OCP. " Copy Login Command" link from the right of the "https://console.apps.silver.devops.gov.bc.ca/"  under the profile name dropdown. This will give a "oc login --token-sdfdsds" command.
b) switch to "-tools" OCP project namespaces of required project. FOI FLOW is on "d7abee-tools" . with command like - " oc project d7abee-tools"

c) to back up request management api , it is    

`oc tag request-management-api:prod-002 request-management-api:prod-002-bu -n d7abee-tools`

c) to back up foi flow web , it is  

`oc tag forms-flow-web:prod forms-flow-web:prod-bu -n d7abee-tools`


*** Now we need to back up the FOI DOCUMENT REVIEWER API as well , so switch to d106d6-tools, since there are changes reviewer_api as well.with command like - " oc project d106d6-tools"

d) to back up reviewer api  , it is  

`oc tag reviewer-api:prod reviewer-api:prod-bu -n d106d6-tools`


 3) Deployment of FOI FLOW FE, BE
------------------------------------------------------
a) switch to "-tools" OCP project namespaces of required project. FOI FLOW is on "d7abee-tools" . with command like - " oc project d7abee-tools"

b) now we need tag the "test" image to "prod" of API

   `oc tag request-management-api:test request-management-api:prod-002 -n d7abee-tools`

c) now we need tag the "test" image to "prod" of FOI FLOW WEB
 
  `oc tag forms-flow-web:test forms-flow-web:prod -n d7abee-tools`


 4) Deployment of Document Reviwwer API -  BE
------------------------------------------------------
so switch to d106d6-tools, since there are changes reviewer_api as well.with command like - " oc project d106d6-tools"

c) now we need tag the "test" image to "prod" of reviewer api
 
  `oc tag reviewer-api:test reviewer-api:prod -n n d106d6-tools`
