### ISSUE TITLE
Unable to change the request to "Response' state

### ISSUE THREAD

**Issue by nimya-aot** [bcgov/foi-flow#4519]
**Describe the bug in current situation**
When an intake user try to change the state from 'Records Review' to 'Response' state 'Save change' button is disabled so user is unable to change it
**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**
Test

**Steps to Reproduce**
1. Go to Ministry user login and take any request which is on 'Call for Records'
2. Change the state to "Records review'
3. Login as IAO user and try to change the state to 'Response'

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbzdWIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ea7a240fe705370b4b41eff5909e2d34b6b5d4ae/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcExWIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ee475a3baedde94b50f7fba45a4af1b8271e5449/image.png)

**Comment by liseandtea** [comment]
Followed the steps to reproduce:
Go to Ministry user login and take any request which is on 'Call for Records'
Change the state to "Records review'
Login as IAO user and try to change the state to 'Response'

Tested on CLB-2023-31008 and CLB-2023-31009 in TEST. Both requests are now doing the expected behaviour. The "Save Change" option on the modal is active and no longer greyed out. I was able to move the request from the 'Records Review' state to the 'Response' state - closing this bug ticket.
