### ISSUE TITLE
Attachments Tab - Upload Slowness / Not Uploading

### ISSUE THREAD

**Issue by KyEggleston** [bcgov/foi-flow#4636]
**Describe the bug in current situation**
General slowness with attachment uploads to Attachment tab. For example, today on PSA-2023-31668 a file was trying to be uploaded that is 88MB, and didn't upload, even after 1+ hours. No errors thrown, just constant uploading. In addition, on Monday COR-2023-33460 had a file of 50MB trying to be uploaded. It did upload, but after 20-25 min. Don't recall this occurring in the past with large files - in TEST it works for me on 207MB file, but takes 10 minutes or so. 

![image](https://github.com/bcgov/foi-flow/assets/117312323/ef67a8e0-7aa2-44bf-ab05-7457b476a8fe)

**Link bug to the User Story**

**Impact of this bug**
Describe the impact, i.e. what the impact is, and number of users impacted. 

**Chance of Occurring (high/medium/low/very low)**

**Pre Conditions: which Env, any pre-requesites or assumptions to execute steps?**

**Steps to Reproduce**

**Actual/ observed behaviour/ results**

**Expected behaviour**
A clear and concise description of what you expected to happen. Use the gherking language. 

**Screenshots/ Visual Reference/ Source**
If applicable, add screenshots to help explain your problem. You an use screengrab.

**Comment by milosdes** [comment]
I tested this a few days ago, last Thursday and Friday - the upload speed via web app was significantly slower. I tried using the fetch API instead of Axios, as I found that some people were reporting issues with slow Axios uploads, but that didn't help. Uploading via 'S3 browser' was significantly faster (about 90 seconds for 269 mb file, and about 60 secs for 20mb file). Same with upload via Postman.

Today the upload speed issues seem to be resolved via the web app? Uploaded 169mb file in under 1:10. See this request: 
https://test.foirequests.gov.bc.ca/foi/reviewrequest/1781

@KyEggleston can you test out the uploads again and/or check-in with users to see if the issue has resolved? If so, it may not be on our end, but it would be keep to keep an eye out and see if this issue reoccurs.

**Comment by KyEggleston** [comment]
The users that had the issue say they haven't noticed it being an issue the past few days - and testing again with various upload sizes it is performing as expected now (largest was 207mb, upload was 23 seconds)

**Comment by KyEggleston** [comment]
Closing ticket, but will monitor to see if issue is recurring.
