### ISSUE TITLE
Analysis of excel conversion to pdf

### ISSUE THREAD

**Issue by divyav-aot** [bcgov/foi-flow#53]
Title of ticket: 

#### Description
Summarize issue 

#### Dependencies
Are there any dependencies?

#### DOD
- [ ] List the items that need to be complete for this ticket to be considered done
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by abin-aot** [comment]
Based on research and many discussions around "Problematic Excel Files", several analysis has been done with below mentioned options.

1. Python UNOCONV + LibreOffice Headless Approach. - direct Excel to PDF conversion
2. Python's EXCEL TO HTML conversion, then HTML to PDF using Libraries such (xls2html etc.) and 
    PDFKIT/WaesyPrint.
3.  .NET Core + Syncfusion
4. Python's pywin32 or xlwings for direct EXCEL to PDF using win32 COM behind the scen

All the analysis has been done around the problematic excel files provided by IAO SMEs and freely available excel files from BC data catalogues. Most of the possible cases has been covered during analysis and its been found that other than options #3 and #4, rest of the options like #1 & # 2 is not converting "problematic excel" files from IAO , due to the fact that they contain MS Office Excel specific extensions like "slicers". Upon investigating further its understood there are compatibility issues with Python unoconv with these extensions or generally to the Linux based/opensource libraries while parsing these types of Microsoft excel files. Which made focus to #3 and #4 only, because #2 option even though it works, code investment is more comparing with others. 

Now, out of #3 and #4 - #4 option has dependency on windows platform(windows docker container) due to the fact that its using Win32 COM. So, this option is not viable from the infrastructure perspective of current BC DevExchange Open shift platform version.

In the end, we decided to move on with Option #3, due to the fact that its working fine with all available excel types at this moment,. Easy manipulation of EXCEL , with comparatively less code investment and overheads. Since those are getting dealt by third part tool(paid) called syncfusion. [](https://www.syncfusion.com/downloads/fileformats ). 

Few other ideas came on to the table like Apache Camel and its been reviewed internally and as well as vendor specific architects team. But Its decided to park it aside and  to go on with minimalistic approach with low overhead & code considering the scenario, requirements on the Miro board for Excel File Conversion. 

For ICalender (.ics) - we have working solution on all platforms - only problematic excel made us to opt for #3, 

Currently known risks with Option #3 - "Even though Syncfusion has support on "All platform based .NET Core", few of its dependencies is throwing errors while dockerizing. This issue has few solutions listed on Syncfusion forums and need to try this out on coming days" . Team decided to bear this risk and go forward on this sprint. 

Tagging Team for better visibility @divyav-aot @sumathi-thirumani-aot @lmullane @acoard-aot

**Comment by lmullane** [comment]
Good summary, @abin-aot 

Thanks for all the analysis work on this team. As discussed we will move forward with option 3. 

cc @m-prodan
