### ISSUE TITLE
iStore Request: Create a Test LAN

### ISSUE THREAD

**Issue by mpilchar** [bcgov/foi-flow#56]
Must have the same network/set up as current LAN

If you can add some sample request folder with files then it will help us to test from our side. Or you can share the files separate.  No need of production data in this LAN.

**Comment by m-prodan** [comment]
After considerable discussion with iStore partners and others - test LAN was determined to not be the most efficient course of action. Shifted to using a virtual shared drive as a testing environment through the VM - access has since been granted as such, and will be closing this ticket with this updated comment.
