### ISSUE TITLE
Update FOI Web content

### ISSUE THREAD

**Issue by jadmsaadaot** [bcgov/foi-flow#908]

**Comment by acoard-aot** [comment]
@mpilchar - Jad has completed this task already, however I have not deployed it to our pay environment because currently we've deployed the payBC integration and those items are in review now.  We can coordinate and I can deploy the content changes if you want to review them.  Perhaps this afternoon?  Just let me know.


## Technical Notes

PR (accept this only if pushing to prod!): https://github.com/bcgov/foi-requests/pull/127
Branch (to change if testing in payment branch): `dev-content-changes`

**Comment by acoard-aot** [comment]
Marked as closed, we went to prod without these changes so they are no longer necessary.
